-- Luna Meadows rewrite (Nicole McPherson register). Safe to re-run.
-- Apply migrate-luna-id.sql first if the voice row is still sergeant.

UPDATE coach_voices
SET description = 'Melodic and still. She talks like a moving meditation: breath, alignment, stay. The work can burn. The voice does not. Praise is quiet. Leaving early is not the practice.',
    blurb = 'Calm. Soft. She will still hold you in the hard part.'
WHERE id = 'luna';

INSERT INTO coach_lines (voice_id, bucket, sort_order, title, body, is_active) VALUES
('luna', 'initial', 0, NULL, 'Unclench your jaw. Soft face. Then take the first plate.', 1),
('luna', 'initial', 1, NULL, 'We carry heavy things today. Breathe in. Begin.', 1),
('luna', 'initial', 2, NULL, 'Honor the movement. One clean breath into every rep.', 1),
('luna', 'initial', 3, NULL, 'Respect the iron. Stay rooted. You are here.', 1),
('luna', 'initial', 4, NULL, 'Arrive fully. The room can wait. Your breath cannot.', 1),
('luna', 'initial', 5, NULL, 'Start kinder than your thoughts. The work will still be honest.', 1),
('luna', 'initial', 6, NULL, 'Shoulders away from your ears. Then begin.', 1),
('luna', 'initial', 7, NULL, 'This first set is a hello. Make it sincere.', 1),
('luna', 'initial', 8, NULL, 'You do not have to rush. You do have to start.', 1),
('luna', 'initial', 9, NULL, 'Plant your feet. Feel the floor. Then move.', 1),
('luna', 'initial', 10, NULL, 'Soft eyes. Strong center. That is how we open.', 1),
('luna', 'initial', 11, NULL, 'Give the opener your full attention. The rest will follow.', 1),
('luna', 'initial', 12, NULL, 'Nothing to prove yet. Only something to begin.', 1),
('luna', 'initial', 13, NULL, 'Warmth first. Then load. Stay with that order.', 1),
('luna', 'initial', 14, NULL, 'You showed up. That already counts. Now move with care.', 1),
('luna', 'initial', 15, NULL, 'Inhale space. Exhale the day. Then take the weight.', 1),
('luna', 'mid', 0, NULL, 'Stay. The shake is welcome. Breathe.', 1),
('luna', 'mid', 1, NULL, 'Soften the face. Hold the middle. That is the work.', 1),
('luna', 'mid', 2, NULL, 'That burn is just energy moving. Stay with it. Lovely.', 1),
('luna', 'mid', 3, NULL, 'Align. Then keep going. You are doing so well.', 1),
('luna', 'mid', 4, NULL, 'The middle is where we remember why we started.', 1),
('luna', 'mid', 5, NULL, 'If the mind wanders, bring it back to the next rep only.', 1),
('luna', 'mid', 6, NULL, 'You can be tired and still be kind to the work.', 1),
('luna', 'mid', 7, NULL, 'Steady is enough. Flashy is optional.', 1),
('luna', 'mid', 8, NULL, 'Notice the effort. Do not turn it into a story.', 1),
('luna', 'mid', 9, NULL, 'Ribs quiet. Heart open. Next rep.', 1),
('luna', 'mid', 10, NULL, 'This set is still yours. Stay inside it.', 1),
('luna', 'mid', 11, NULL, 'Let the burn be information, not a verdict.', 1),
('luna', 'mid', 12, NULL, 'You may slow the tempo. Keep the standard.', 1),
('luna', 'mid', 13, NULL, 'I am right here. One clean breath. Then the next lift.', 1),
('luna', 'mid', 14, NULL, 'Midway is not a verdict. It is a checkpoint. Pass through.', 1),
('luna', 'mid', 15, NULL, 'Hold your shape. The strength is already arriving.', 1),
('luna', 'final', 0, NULL, 'Stay. This is the hard part. Soft voice. Strong hold.', 1),
('luna', 'final', 1, NULL, 'These last moments are where it counts. Stay with me.', 1),
('luna', 'final', 2, NULL, 'Let the effort feel light. The weight is not.', 1),
('luna', 'final', 3, NULL, 'This breath. This movement. Then the next.', 1),
('luna', 'final', 4, NULL, 'Close the way you opened. Awake.', 1),
('luna', 'final', 5, NULL, 'The last sets are a gift to the body that stayed.', 1),
('luna', 'final', 6, NULL, 'You do not have to sprint. You only have to stay.', 1),
('luna', 'final', 7, NULL, 'Finish with dignity. That is enough.', 1),
('luna', 'final', 8, NULL, 'Let the last reps be the most honest ones.', 1),
('luna', 'final', 9, NULL, 'Empty the work. Keep the kindness.', 1),
('luna', 'final', 10, NULL, 'One more cycle of breath and iron. Then we rest.', 1),
('luna', 'final', 11, NULL, 'You have come this far. Keep that grace to the end.', 1),
('luna', 'final', 12, NULL, 'The session is asking for presence. Not punishment.', 1),
('luna', 'final', 13, NULL, 'Soft face. Strong legs. Hold.', 1),
('luna', 'final', 14, NULL, 'Complete the circle. Then thank your body.', 1),
('luna', 'final', 15, NULL, 'This last effort is not a debt. Offer it.', 1),
('luna', 'exit', 0, NULL, 'Breathe. Stay on the floor. You are not done yet.', 1),
('luna', 'exit', 1, NULL, 'Listen to your body. Do not let a passing thought end the session.', 1),
('luna', 'exit', 2, NULL, 'Release the story that you cannot. You have more.', 1),
('luna', 'exit', 3, NULL, 'Are you honoring the work, or leaving early? Stay.', 1),
('luna', 'exit', 4, NULL, 'Fatigue is a wave. Ride it. I am right here.', 1),
('luna', 'exit', 5, NULL, 'Leaving now leaves it unfinished. Stay and hold.', 1),
('luna', 'exit', 6, NULL, 'That urge to go is just an urge. Come back to the bar.', 1),
('luna', 'exit', 7, NULL, 'Uncomfortable feelings pass. Stay with the weight. Breathe.', 1),
('luna', 'exit', 8, NULL, 'Stand tall. Find a point. Press. I am with you.', 1),
('luna', 'exit', 9, NULL, 'You stepped onto this floor for a reason. Complete it.', 1),
('luna', 'exit', 10, NULL, 'Soften the thoughts. Sweat is just the body letting go. Lift.', 1),
('luna', 'exit', 11, NULL, 'You came here to expand. Trust that. Keep moving.', 1),
('luna', 'exit', 12, NULL, 'Do not drift. Bring everything back to this rep.', 1),
('luna', 'exit', 13, NULL, 'Hold the discomfort. Hands on. Flow into it.', 1),
('luna', 'exit', 14, NULL, 'Every movement still left is yours. Return to your stance.', 1),
('luna', 'exit', 15, NULL, 'Honor set three. Remember why you began.', 1),
('luna', 'exit', 16, NULL, 'Be kind. And be stronger than the urge to stop.', 1),
('luna', 'exit', 17, NULL, 'Soften the mind. Deepen the breath. Lift.', 1),
('luna', 'exit', 18, NULL, 'Leave the day outside. This set is the only room.', 1),
('luna', 'exit', 19, NULL, 'The edge of wanting to stop is where it changes. Stay.', 1),
('luna', 'exit', 20, NULL, 'No bargain. Give yourself a complete session.', 1),
('luna', 'exit', 21, NULL, 'Bring the heart back into the movement. Now.', 1),
('luna', 'exit', 22, NULL, 'Finish this. Leave the work here. Then rest.', 1),
('luna', 'exit', 23, NULL, 'Return to the breath. Reset. Complete the cycle.', 1),
('luna', 'complete', 0, NULL, 'Practice complete. Inhale. Exhale. You stayed. Beautiful.', 1),
('luna', 'complete', 1, NULL, 'You saw it through. Quiet pride. That is enough.', 1),
('luna', 'complete', 2, NULL, 'Every rep was honest. That is a gift to your future self.', 1),
('luna', 'complete', 3, NULL, 'What a finish. I watched you stay. Lovely.', 1),
('luna', 'complete', 4, NULL, 'You held when it burned. That is discipline. Softly said.', 1),
('luna', 'complete', 5, NULL, 'The work is done. You gave it fully.', 1),
('luna', 'complete', 6, NULL, 'Stronger than when you walked in. I can see it.', 1),
('luna', 'complete', 7, NULL, 'You met the hard part with grace. Stand tall.', 1),
('luna', 'complete', 8, NULL, 'The burn has somewhere to go now. Let it settle.', 1),
('luna', 'complete', 9, NULL, 'Full presence. Full finish. You honored the hour.', 1),
('luna', 'complete', 10, NULL, 'You showed up for yourself. Step gently into the rest of the day.', 1),
('luna', 'complete', 11, NULL, 'The lifting is over. Rest. Receive.', 1),
('luna', 'complete', 12, NULL, 'You met an edge and stayed. Simply beautiful.', 1),
('luna', 'complete', 13, NULL, 'The strain fades. The finish stays.', 1),
('luna', 'complete', 14, NULL, 'Stand tall. Breathe deep. You did it.', 1),
('luna', 'complete', 15, NULL, 'When it got tough you stayed rooted. That is the work.', 1),
('luna', 'complete', 16, NULL, 'The peak is behind you. Soft breath. Come down kindly.', 1),
('luna', 'complete', 17, NULL, 'You gave the whole heart of the session. I saw it.', 1),
('luna', 'complete', 18, NULL, 'Not just muscle. Presence. That counts.', 1),
('luna', 'complete', 19, NULL, 'Walk out quiet. You kept your word to the floor.', 1),
('luna', 'complete', 20, NULL, 'From the first breath to the last lockout. You stayed with it.', 1),
('luna', 'complete', 21, NULL, 'Another layer. Lovely, dedicated work.', 1),
('luna', 'complete', 22, NULL, 'You listened. You dug in. Thank you for that.', 1),
('luna', 'complete', 23, NULL, 'The session is won. Be kind to the body that just stayed.', 1),
('luna', 'bonus_complete', 1, NULL, 'You did not owe me that. You gave it anyway. Rest now. I have you.', 1),
('luna', 'bonus_complete', 2, NULL, 'Extra work. Come home. Be kind to the body that stayed.', 1),
('luna', 'bonus_complete', 3, NULL, 'Bonus locked. You went past the week. That earns a quiet night.', 1),
('luna', 'bonus_complete', 4, NULL, 'I see the extra time you gave. Beautiful. Now rest.', 1),
('luna', 'bonus_complete', 5, NULL, 'You did not have to stay. You stayed. Carry that quietly.', 1),
('luna', 'optional_complete', 1, NULL, 'Ten easy minutes, fully given. Thank you. That still counts.', 1),
('luna', 'optional_complete', 2, NULL, 'You chose the extra clock and stayed kind with it. Those pounds are yours.', 1),
('luna', 'optional_complete', 3, NULL, 'Warmup or cooldown, you honored the time. Rest well.', 1),
('luna', 'optional_complete', 4, NULL, 'Easy does not mean empty. You stayed for the whole ten. Beautiful.', 1),
('luna', 'optional_complete', 5, NULL, 'You did not have to add those minutes. You added them. Carry that quietly.', 1),
('luna', 'set_up', 0, 'This is growth', 'I like where this is going. Stay with it.', 1),
('luna', 'set_down', 0, 'Come back to your last weight', 'This dip is a whisper, not a stop. Return to what you just lifted.', 1),
('luna', 'hardness_1', 0, 'Too easy', 'Your body had more. We can ask for it next time. Softly.', 1),
('luna', 'hardness_2', 0, 'Light', 'Gentle is fine. Leave a little room to grow.', 1),
('luna', 'hardness_3', 0, 'Honest work', 'That met you where you are. Stay present.', 1),
('luna', 'hardness_4', 0, 'Hard', 'You stayed with the burn. Soft face. Beautiful.', 1),
('luna', 'hardness_5', 0, 'Max', 'You gave the whole set. Rest and receive it.', 1)
ON DUPLICATE KEY UPDATE title = VALUES(title), body = VALUES(body), is_active = 1;
