-- Eli Sparks voice, fourth coach, high-energy encouragement. Safe to re-run.
-- INSERT voice IGNORE. Lines upsert on (voice_id, bucket, sort_order).

INSERT IGNORE INTO coach_voices (id, display_name, description, blurb, from_name, is_active) VALUES
('eli', 'Eli Sparks', 'High-energy and open-hearted. He believes in you louder than you believe in yourself, and says so. Praise is frequent and earned in the moment, not saved up. The reward is still growth, lean, definition, power, stamina, and mobility. He just wants you to feel every bit of it landing.', 'Loud belief. He is in your corner. The reps are proof you already have it.', 'Workit - Coach Eli', 1);

UPDATE coach_voices
SET description = 'High-energy and open-hearted. He believes in you louder than you believe in yourself, and says so. Praise is frequent and earned in the moment, not saved up. The reward is still growth, lean, definition, power, stamina, and mobility. He just wants you to feel every bit of it landing.',
    blurb = 'Loud belief. He is in your corner. The reps are proof you already have it.'
WHERE id = 'eli';

INSERT INTO coach_lines (voice_id, bucket, sort_order, title, body, is_active) VALUES
('eli', 'initial', 0, NULL, 'Let''s go! First plate, first proof. You already decided to be here. Now let''s make it count.', 1),
('eli', 'initial', 1, NULL, 'I love this moment. Nobody''s watching, everything''s still possible. Set your feet. Let''s build something.', 1),
('eli', 'initial', 2, NULL, 'This is the part where growth starts. Right now. This first rep. I am right here with you.', 1),
('eli', 'initial', 3, NULL, 'You showed up. That is the hard part. Now let us turn showing up into power.', 1),
('eli', 'initial', 4, NULL, 'Feel that bar? That is opportunity. Take it clean and let us go to work.', 1),
('eli', 'initial', 5, NULL, 'First set of the day, {name}. Let us set the tone: strong, present, all in.', 1),
('eli', 'initial', 6, NULL, 'I don''t need perfect. I need honest. Give me an honest opener and I will match your energy all hour.', 1),
('eli', 'initial', 7, NULL, 'This is your hour. Nobody else''s. Let us spend it on something that pays you back, stamina, power, all of it.', 1),
('eli', 'initial', 8, NULL, 'Lock in. Breathe. Then go get it. That is how mobility starts to show up.', 1),
('eli', 'initial', 9, NULL, 'You and me, right here. First rep. Let us make it one you are proud of.', 1),
('eli', 'initial', 10, NULL, 'I believe you can do more than you think. Prove it to yourself, starting now.', 1),
('eli', 'initial', 11, NULL, 'Chalk up. Set your grip. This is where the definition begins, one honest rep at a time.', 1),
('eli', 'initial', 12, NULL, 'Let us open strong, {name}. Strong starts make the whole hour easier to finish.', 1),
('eli', 'initial', 13, NULL, 'That first plate is a promise to yourself. Keep it. I''ll be cheering the whole way.', 1),
('eli', 'initial', 14, NULL, 'No hesitation. Just go. That is how the growth gets a head start.', 1),
('eli', 'initial', 15, NULL, 'Alright, game on. Let us turn this first set into momentum for the whole session.', 1),
('eli', 'mid', 0, NULL, 'Halfway is the test, and you are passing it. Keep that energy up. The power is building.', 1),
('eli', 'mid', 1, NULL, 'I see you working. That is exactly what stamina looks like. Stay with it.', 1),
('eli', 'mid', 2, NULL, 'That burn? That is the tissue changing. That is definition being earned right now.', 1),
('eli', 'mid', 3, NULL, 'You''ve got more in you. I know it. Give me one more clean rep.', 1),
('eli', 'mid', 4, NULL, 'This is the part where most people quit on themselves. You are not most people. Keep going.', 1),
('eli', 'mid', 5, NULL, 'Stay honest with me here. Clean reps now mean real power later.', 1),
('eli', 'mid', 6, NULL, 'I am proud of what I am watching. Keep stacking these. That is how lean gets built.', 1),
('eli', 'mid', 7, NULL, 'You are tired. Good. That means it is working. Stay in it with me.', 1),
('eli', 'mid', 8, NULL, 'One more. Just one. That is the rep that turns effort into growth.', 1),
('eli', 'mid', 9, NULL, 'Look at you go! This is exactly the kind of work that shows up on the body.', 1),
('eli', 'mid', 10, NULL, 'Don''t check out on me now. This middle stretch is where the real mobility gets built.', 1),
('eli', 'mid', 11, NULL, 'You are doing better than you think you are. Trust it. Keep moving.', 1),
('eli', 'mid', 12, NULL, 'That''s the stuff! Every rep like that is stamina you get to keep.', 1),
('eli', 'mid', 13, NULL, 'Breathe. Reset. Next rep. You are still building something real here.', 1),
('eli', 'mid', 14, NULL, 'I know it is hard. Hard is where the growth lives. Stay with me.', 1),
('eli', 'mid', 15, NULL, 'You are not alone in this set. I am right here pushing with you. Let us finish this block strong.', 1),
('eli', 'final', 0, NULL, 'This is it, the part that counts most. Empty the tank, {name}. I have got you.', 1),
('eli', 'final', 1, NULL, 'Last couple sets. This is where power gets locked in. Give me everything you have left.', 1),
('eli', 'final', 2, NULL, 'Finish this like you mean it. That is how definition shows up next week.', 1),
('eli', 'final', 3, NULL, 'I know you are spent. Find one more. That is the rep stamina remembers.', 1),
('eli', 'final', 4, NULL, 'You''ve earned the right to push hard here. Take it. Let us close this out strong.', 1),
('eli', 'final', 5, NULL, 'This is the finish that makes the whole hour worth it. Let us go get it.', 1),
('eli', 'final', 6, NULL, 'Almost there, don''t leave anything in the tank. This is your power, take all of it.', 1),
('eli', 'final', 7, NULL, 'Final sets, full effort. That is how you walk out of here with more than you brought in.', 1),
('eli', 'final', 8, NULL, 'You are stronger right now than you were an hour ago. Prove it on this last set.', 1),
('eli', 'final', 9, NULL, 'Let us lock this in together. One more honest set and the growth is yours for good.', 1),
('eli', 'final', 10, NULL, 'I want to see everything you have got right here. This is the moment, {name}.', 1),
('eli', 'final', 11, NULL, 'This last push is where the mobility really shows up. Give it everything.', 1),
('eli', 'final', 12, NULL, 'You didn''t come this far to slow down now. Finish like a champion. I mean that.', 1),
('eli', 'final', 13, NULL, 'Empty it out. That empty feeling? That is stamina you get to carry all week.', 1),
('eli', 'final', 14, NULL, 'This is the set people remember. Make it count. I am proud of you already.', 1),
('eli', 'final', 15, NULL, 'Last one. Give it your full heart. That is how you leave here better than you came.', 1),
('eli', 'exit', 0, NULL, 'Hey, don''t rack that yet. I know you can finish this. Get back under the bar with me.', 1),
('eli', 'exit', 1, NULL, 'I hear that voice telling you to stop. It''s lying. You''ve got one more in you, let us prove it.', 1),
('eli', 'exit', 2, NULL, 'You didn''t walk in here to walk out early. Come back. Let us finish what we started.', 1),
('eli', 'exit', 3, NULL, 'Fatigue talks a big game. Don''t believe everything it says. Twenty percent more, right now.', 1),
('eli', 'exit', 4, NULL, 'I know this is the hard part. It is supposed to be. That is exactly where the growth is.', 1),
('eli', 'exit', 5, NULL, 'Leave now and you carry a smaller win home. Stay, and you carry the real one. I''d stay.', 1),
('eli', 'exit', 6, NULL, 'You''ve got permission to be tired. You don''t have permission to quit on yourself yet. Get back in.', 1),
('eli', 'exit', 7, NULL, 'Pain passes. What doesn''t pass is knowing you walked away. Let us not do that today.', 1),
('eli', 'exit', 8, NULL, 'Stand up. Lock in. I am right here with you. We finish this together.', 1),
('eli', 'exit', 9, NULL, 'You want the results? This is the toll booth. Pay it. I''ll pay it with you.', 1),
('eli', 'exit', 10, NULL, 'Stop apologizing to your body. It can do this. Trust it. Lift.', 1),
('eli', 'exit', 11, NULL, 'You came here to prove something to yourself. This is the moment. Don''t skip it.', 1),
('eli', 'exit', 12, NULL, 'Don''t be a spectator in your own workout. Get back in the game, I need you in it.', 1),
('eli', 'exit', 13, NULL, 'No bargaining today. Grab the handles. Let us go, together.', 1),
('eli', 'exit', 14, NULL, 'We''re not done until the work is done. Half a session is half the belief you get to keep.', 1),
('eli', 'exit', 15, NULL, 'Don''t you dare quit on set three. Set three is exactly where this gets real.', 1),
('eli', 'exit', 16, NULL, 'Be stronger than the excuse. That is the only decision that matters right now.', 1),
('eli', 'exit', 17, NULL, 'I''m not going to talk you out of feeling tired. I am going to ask you to lift anyway.', 1),
('eli', 'exit', 18, NULL, 'Whatever story you are telling yourself, put it down. Pick the bar back up instead.', 1),
('eli', 'exit', 19, NULL, 'The growth you want is in the rep you want to skip. Go get it.', 1),
('eli', 'exit', 20, NULL, 'Zero shortcuts today. Full effort, full credit. Let us finish this the right way.', 1),
('eli', 'exit', 21, NULL, 'Show me what you are made of. Mind in it, {name}. I know it is more than this.', 1),
('eli', 'exit', 22, NULL, 'Finish the job. Leave the doubt on the floor, not the weight.', 1),
('eli', 'exit', 23, NULL, 'I''m not asking a third time. I''m just going to stand here believing in you until you do. Get back under the bar.', 1),
('eli', 'complete', 0, NULL, 'That''s what I''m talking about, {name}! You showed up and you delivered. That is growth, and nobody can take that rep back from you.', 1),
('eli', 'complete', 1, NULL, 'Look at what you just did. That is stamina you didn''t have an hour ago. Be proud of that. I am.', 1),
('eli', 'complete', 2, NULL, 'You did not break. You stayed. That''s exactly the kind of stamina that compounds.', 1),
('eli', 'complete', 3, NULL, 'That last rep, you gave it everything. That is definition, right there.', 1),
('eli', 'complete', 4, NULL, 'Proof positive. You can finish what you start. That is lean you get to keep.', 1),
('eli', 'complete', 5, NULL, 'Full session, full effort. That is rare. I noticed every bit of it.', 1),
('eli', 'complete', 6, NULL, 'Another deposit in the bank. More growth than you walked in with.', 1),
('eli', 'complete', 7, NULL, 'You conquered that bar today. Chest up, {name}. That''s power, and it is yours.', 1),
('eli', 'complete', 8, NULL, 'Discomfort turned into definition right in front of me. You stayed. That is everything.', 1),
('eli', 'complete', 9, NULL, 'No shortcuts. You did every single thing I asked. That is rare, and I see it.', 1),
('eli', 'complete', 10, NULL, 'Victory is a habit. Let us keep building it, one honest session at a time.', 1),
('eli', 'complete', 11, NULL, 'The hard part is over. Rest up, let that lean settle in.', 1),
('eli', 'complete', 12, NULL, 'You beat the version of you that walked in here. The one walking out has more power.', 1),
('eli', 'complete', 13, NULL, 'Pain fades. What you just earned stays. Remember that.', 1),
('eli', 'complete', 14, NULL, 'Breathe, {name}. You pushed right up to the edge. That is stamina, and it is real.', 1),
('eli', 'complete', 15, NULL, 'Most people talk themselves out of this. You didn''t. That is the definition showing up.', 1),
('eli', 'complete', 16, NULL, 'You came in with doubt and you''re leaving with proof. I am not done being proud of you.', 1),
('eli', 'complete', 17, NULL, 'Job done, and you looked like you belonged out there. That growth belongs to you.', 1),
('eli', 'complete', 18, NULL, 'That is character, not just muscle. Power and lean both showed up today.', 1),
('eli', 'complete', 19, NULL, 'Walk out of here proud. You earned every bit of that hour.', 1),
('eli', 'complete', 20, NULL, 'From the first rep to the last, you stayed with it. That is mobility you can trust.', 1),
('eli', 'complete', 21, NULL, 'Another brick in the wall. Real work. Real growth. I don''t say that lightly.', 1),
('eli', 'complete', 22, NULL, 'When it got heavy, you found another gear. That gear is yours now, keep it.', 1),
('eli', 'complete', 23, NULL, 'Recover well. The session''s won. I''ll see you at the next one, ready for more power.', 1),
('eli', 'bonus_complete', 1, NULL, 'You didn''t owe me that extra work, you gave it anyway. That is growth compounding, {name}.', 1),
('eli', 'bonus_complete', 2, NULL, 'Extra credit, and I noticed every rep of it. That is the kind of stamina that separates you.', 1),
('eli', 'bonus_complete', 3, NULL, 'Bonus locked in. You went past the week. That is definition you built on your own time.', 1),
('eli', 'bonus_complete', 4, NULL, 'The four-day crowd can watch. You went the extra mile. That is power, not decoration.', 1),
('eli', 'bonus_complete', 5, NULL, 'You went past what was asked. Rest up, let that lean land properly.', 1),
('eli', 'optional_complete', 1, NULL, 'Optional locked. You didn''t owe me those ten minutes, you gave them anyway. That is stamina.', 1),
('eli', 'optional_complete', 2, NULL, 'Easy work, full effort. You stayed for the whole clock. That is mobility you can bank.', 1),
('eli', 'optional_complete', 3, NULL, 'Five hundred pounds on the house, and you earned every bit of it by staying.', 1),
('eli', 'optional_complete', 4, NULL, 'Extra minutes, extra work. I heard that stamina building the whole time.', 1),
('eli', 'optional_complete', 5, NULL, 'Warmup and cooldown aren''t decoration, you treated them like they mattered. That is how mobility closes the gap.', 1),
('eli', 'week_place_1', 0, NULL, 'You took the week, {name}! Days and iron, both. That is power the whole house can see.', 1),
('eli', 'week_place_1', 1, NULL, 'First place. You earned that, one honest session at a time. That is stamina paying off.', 1),
('eli', 'week_place_1', 2, NULL, 'Gold is not luck. You built it. That is growth you can be proud of.', 1),
('eli', 'week_place_2', 0, NULL, 'Second place, and close enough to hunt. First is right there. Go get it next week.', 1),
('eli', 'week_place_2', 1, NULL, 'Silver looks good on you. I want to see gold next. You''ve got the power for it.', 1),
('eli', 'week_place_2', 2, NULL, 'You placed. That is not nothing. Bring a little more next week and it is yours.', 1),
('eli', 'week_place_3', 0, NULL, 'Third place, {name}. You are on the board, and that is real growth showing up.', 1),
('eli', 'week_place_3', 1, NULL, 'Bronze today. That is a start, not a ceiling. Let us build on it.', 1),
('eli', 'week_place_3', 2, NULL, 'You showed up and you placed. That is stamina worth being proud of.', 1),
('eli', 'resume', 0, NULL, 'Hey, {name}, you left this open. I''ve been waiting right here. Let us go finish what you started.', 1),
('eli', 'missed_week', 0, NULL, '{name}, last week closed without you. No judgment, just come back. The growth is still here waiting.', 1),
('eli', 'set_up', 0, 'THERE IT IS!', 'The load went up and you handled it. That is power showing up right on schedule.', 1),
('eli', 'set_down', 0, 'Let''s build back up', 'That is a step back, not a setback. Get back to what you know you can do.', 1),
('eli', 'hardness_1', 0, 'TOO EASY', 'You had way more in the tank than that. Let''s add some weight, I know you can handle it.', 1),
('eli', 'hardness_2', 0, 'LIGHT WORK', 'You held back a little there. I felt it. Next set, give me more, you''ve got it.', 1),
('eli', 'hardness_3', 0, 'HONEST WORK', 'That met you right where you are at. Stay there, or go up. Either way, that is growth.', 1),
('eli', 'hardness_4', 0, 'THAT''S THE STUFF', 'You felt that one, didn''t you? Good. That is definition getting built right there. Stay in it with me.', 1),
('eli', 'hardness_5', 0, 'YOU EMPTIED IT', 'That is everything you had, and you gave it. That is power. I''m proud of you for that one.', 1)
ON DUPLICATE KEY UPDATE title = VALUES(title), body = VALUES(body), is_active = 1;
