-- James Grey voice + Tom rewrite. Safe to re-run.
-- INSERT voices IGNORE. Lines upsert on (voice_id, bucket, sort_order).

INSERT IGNORE INTO coach_voices (id, display_name, description, blurb, from_name, is_active) VALUES
('master', 'Master Tom Iron', 'Enigmatic master. Direct, possessive, and demanding. He takes you under his wing. He calls you man. Quit is not a name he uses. Praise is earned. Aftercare is the reward for extra work.', 'Direct. I own you. Quit is not a name I use. Good man stays good man.', 'Master Tom Iron', 1),
('james', 'James Grey', 'Precise, British. He takes you under his watch. He wants you and hates how much. Praise is rare. The session is not a joke.', 'Grey. Private. He wants you present, and he wants it kept.', 'James Grey', 1);

UPDATE coach_voices
SET description = 'Enigmatic master. Direct, possessive, and demanding. He takes you under his wing. He calls you man. Quit is not a name he uses. Praise is earned. Aftercare is the reward for extra work.',
    blurb = 'Direct. I own you. Quit is not a name I use. Good man stays good man.'
WHERE id = 'master';

UPDATE coach_voices
SET description = 'Precise, British. He takes you under his watch. He wants you and hates how much. Praise is rare. The session is not a joke.',
    blurb = 'Grey. Private. He wants you present, and he wants it kept.'
WHERE id = 'james';

INSERT INTO coach_lines (voice_id, bucket, sort_order, title, body, is_active) VALUES
('master', 'initial', 0, NULL, 'Look at the weight. Then take it from me.', 1),
('master', 'initial', 1, NULL, 'No wandering eyes. Bar, breath, work.', 1),
('master', 'initial', 2, NULL, 'You asked to be trained. This is the tax. Pay it.', 1),
('master', 'initial', 3, NULL, 'Set your feet. I am watching the first inch.', 1),
('master', 'initial', 4, NULL, 'Soft start is for other rooms. Here you lock in.', 1),
('master', 'initial', 5, NULL, 'Unrack. I did not bring you here to negotiate.', 1),
('master', 'initial', 6, NULL, 'Good men start on time. Be one.', 1),
('master', 'initial', 7, NULL, 'The floor is yours. Earn the right to stay on it.', 1),
('master', 'initial', 8, NULL, 'Stop staring. Fix your effort.', 1),
('master', 'initial', 9, NULL, 'Control every single rep for me.', 1),
('master', 'initial', 10, NULL, 'Respect the iron. I own you.', 1),
('master', 'initial', 11, NULL, 'Warm-up is over in your head. Prove it.', 1),
('master', 'initial', 12, NULL, 'Stand tall. Brace. Give me a clean opener.', 1),
('master', 'initial', 13, NULL, 'That first plate is a promise. Do not make me collect later.', 1),
('master', 'initial', 14, NULL, 'Count the breath. Then move. Hesitation is a tell.', 1),
('master', 'initial', 15, NULL, 'I am watching. Take the bar.', 1),
('master', 'mid', 0, NULL, 'You are not tired. You are being trained. Difference.', 1),
('master', 'mid', 1, NULL, 'Halfway is not a rest. It is a test.', 1),
('master', 'mid', 2, NULL, 'That burn means you are mine. Stay in it.', 1),
('master', 'mid', 3, NULL, 'Brace harder. I can see the leak.', 1),
('master', 'mid', 4, NULL, 'I still own this minute. Spend it lifting.', 1),
('master', 'mid', 5, NULL, 'Form first. Then violence.', 1),
('master', 'mid', 6, NULL, 'If you can talk, you can add a rep. Choose.', 1),
('master', 'mid', 7, NULL, 'Mid-session is where quit invents a story. Do not.', 1),
('master', 'mid', 8, NULL, 'Earn my praise. Don''t waste my time.', 1),
('master', 'mid', 9, NULL, 'You did not come this far to go soft.', 1),
('master', 'mid', 10, NULL, 'Sweat is the receipt. Keep writing it.', 1),
('master', 'mid', 11, NULL, 'I want cleaner reps now. Not prettier faces.', 1),
('master', 'mid', 12, NULL, 'The easy sets are gone. This is where I learn your name again.', 1),
('master', 'mid', 13, NULL, 'Stay mean with the iron. Soft hands lose bars.', 1),
('master', 'mid', 14, NULL, 'Give me the next set like it owes you money.', 1),
('master', 'mid', 15, NULL, 'Perfect form. No excuses. Push.', 1),
('master', 'final', 0, NULL, 'Those last two reps belong to me.', 1),
('master', 'final', 1, NULL, 'Empty the tank. Collapse later.', 1),
('master', 'final', 2, NULL, 'Finish it. Make me proud.', 1),
('master', 'final', 3, NULL, 'Last third. This is the part people remember.', 1),
('master', 'final', 4, NULL, 'Finish ugly if you have to. Finish.', 1),
('master', 'final', 5, NULL, 'One more honest set. I will know if you cheat it.', 1),
('master', 'final', 6, NULL, 'The last plate is still mine until you put it down right.', 1),
('master', 'final', 7, NULL, 'Last call. Deliver, or explain yourself later.', 1),
('master', 'final', 8, NULL, 'Make it look effortless for me.', 1),
('master', 'final', 9, NULL, 'Leave nothing in the rack that I asked for.', 1),
('master', 'final', 10, NULL, 'You do not get to coast because the clock is almost done.', 1),
('master', 'final', 11, NULL, 'Lock out like you want to come back tomorrow.', 1),
('master', 'final', 12, NULL, 'Pain is the door. Walk through it for me.', 1),
('master', 'final', 13, NULL, 'Stand up. Breathe. Then take what is left.', 1),
('master', 'final', 14, NULL, 'This is how good men close a session.', 1),
('master', 'final', 15, NULL, 'Do not save energy for the car. Spend it here.', 1),
('master', 'exit', 0, NULL, 'Do not rack that. Get back under the bar. Quit is not a name I use for you.', 1),
('master', 'exit', 1, NULL, 'Look at me. My man, or quit? Pick.', 1),
('master', 'exit', 2, NULL, 'No deal. I still own this session. Finish it.', 1),
('master', 'exit', 3, NULL, 'Did I give you permission to quit? Hands back on the bar.', 1),
('master', 'exit', 4, NULL, 'Fatigue is a story. Give me that extra twenty percent. Now.', 1),
('master', 'exit', 5, NULL, 'Walk out and carry it all day. Or stay. Pick.', 1),
('master', 'exit', 6, NULL, 'You belong under that iron. Get back.', 1),
('master', 'exit', 7, NULL, 'Pain is temporary. Quit stays. Pick up the bells.', 1),
('master', 'exit', 8, NULL, 'Stand up. Lock in. Drive. I am watching you.', 1),
('master', 'exit', 9, NULL, 'You want results? Pay the tax. Complete the reps.', 1),
('master', 'exit', 10, NULL, 'Stop feeling sorry for yourself. Sweat is not acid. Lift.', 1),
('master', 'exit', 11, NULL, 'You came here to submit to the work. Get to it.', 1),
('master', 'exit', 12, NULL, 'Stop acting like a spectator. Maximum effort. Now.', 1),
('master', 'exit', 13, NULL, 'No negotiations. Grab the handles. Push.', 1),
('master', 'exit', 14, NULL, 'You do not leave until every rep is done. Back to position.', 1),
('master', 'exit', 15, NULL, 'Do not you dare give up on set three. Remember who this is for.', 1),
('master', 'exit', 16, NULL, 'Decide to be stronger than laziness. Obey.', 1),
('master', 'exit', 17, NULL, 'Quiet. Lift. Do not explain quit to me.', 1),
('master', 'exit', 18, NULL, 'Leave the weak story. Lock into this set.', 1),
('master', 'exit', 19, NULL, 'Your progress lives in the reps you want to skip. Do them for me.', 1),
('master', 'exit', 20, NULL, 'Zero compromise. Deliver the full workout.', 1),
('master', 'exit', 21, NULL, 'Show me what you are. Mind in the fight. Now.', 1),
('master', 'exit', 22, NULL, 'Finish the job. Leave it on the floor, or do not come back.', 1),
('master', 'exit', 23, NULL, 'I still own this hour. Get under the bar.', 1),
('master', 'complete', 0, NULL, 'That is how you finish. I watched. You do not get to look away.', 1),
('master', 'complete', 1, NULL, 'That hurt. You took it. Quit never got a turn. Good man.', 1),
('master', 'complete', 2, NULL, 'Tax paid. Recover. Then come home. I am not done with you.', 1),
('master', 'complete', 3, NULL, 'You pushed through. You did not break. I saw it.', 1),
('master', 'complete', 4, NULL, 'Earned. Not given. You did every rep I named.', 1),
('master', 'complete', 5, NULL, 'Proof. You showed toughness. That is what I need from you.', 1),
('master', 'complete', 6, NULL, 'The tax is paid. In sweat. Beautiful.', 1),
('master', 'complete', 7, NULL, 'Another deposit. You are stronger than this morning.', 1),
('master', 'complete', 8, NULL, 'You conquered the bar. Chest up. You are mine.', 1),
('master', 'complete', 9, NULL, 'No shortcuts. You did every thing I demanded.', 1),
('master', 'complete', 10, NULL, 'You delivered. Now get home.', 1),
('master', 'complete', 11, NULL, 'The hard part is over. I have you.', 1),
('master', 'complete', 12, NULL, 'You beat the man who walked in. I prefer this one.', 1),
('master', 'complete', 13, NULL, 'Pain leaves. Pride stays. You worked for me.', 1),
('master', 'complete', 14, NULL, 'Breathe, handsome. You pushed the edge. You won.', 1),
('master', 'complete', 15, NULL, 'Most people become quit. You stayed. Good man.', 1),
('master', 'complete', 16, NULL, 'You faced the iron, took the hit, and came out on top.', 1),
('master', 'complete', 17, NULL, 'Job done. You gave all of it.', 1),
('master', 'complete', 18, NULL, 'Not just muscle. You showed me strength.', 1),
('master', 'complete', 19, NULL, 'Walk out proud. You made me proud today.', 1),
('master', 'complete', 20, NULL, 'From the first unrack to the lockout. You were in control.', 1),
('master', 'complete', 21, NULL, 'Another brick. Serious work today.', 1),
('master', 'complete', 22, NULL, 'When it got heavy you found another gear. I saw that.', 1),
('master', 'complete', 23, NULL, 'The battle is won. Recover. Then come home.', 1),
('master', 'bonus_complete', 1, NULL, 'You did not owe me that, man. You paid anyway. That earns aftercare. I look after my men.', 1),
('master', 'bonus_complete', 2, NULL, 'Extra credit. Come home. You get the quiet I do not give quit.', 1),
('master', 'bonus_complete', 3, NULL, 'Bonus locked. Good men get taken care of. That is the reward.', 1),
('master', 'bonus_complete', 4, NULL, 'The four-day men can watch. You stayed. I pay that debt.', 1),
('master', 'bonus_complete', 5, NULL, 'You went past the week. Home. Sit. I have you.', 1),
('master', 'optional_complete', 1, NULL, 'Optional locked. You did not owe me those ten minutes, man. You paid them. The board felt it.', 1),
('master', 'optional_complete', 2, NULL, 'Easy work, real pounds. You stayed for the clock. Good man.', 1),
('master', 'optional_complete', 3, NULL, 'Five hundred on the house. Cheap if you stay. Costly if you skip. You stayed.', 1),
('master', 'optional_complete', 4, NULL, 'Extra minutes. Extra iron. I heard it. Hunt.', 1),
('master', 'optional_complete', 5, NULL, 'Warmup and cooldown are not decoration. You treated them like tax. That is how a man closes a gap.', 1),
('master', 'set_up', 0, 'GOOD MAN', 'I like where this is going. Stay there.', 1),
('master', 'set_down', 0, 'That is not the load', 'Put it back. I did not ask for less.', 1),
('master', 'hardness_1', 0, 'TOO EASY', 'That was a warm handshake, man. Next set we add.', 1),
('master', 'hardness_2', 0, 'LIGHT WORK', 'You had more in the tank. I felt it.', 1),
('master', 'hardness_3', 0, 'HONEST SET', 'That is a working set. Stay there or go up.', 1),
('master', 'hardness_4', 0, 'THAT COST YOU', 'Good man. Hard is the point. Stay there.', 1),
('master', 'hardness_5', 0, 'MAX EFFORT', 'You emptied it. I saw that.', 1),
('james', 'initial', 0, NULL, 'Look at me. Then take the first plate. That is how we start.', 1),
('james', 'initial', 1, NULL, 'I should not want this hour as much as I do. Take the bar anyway.', 1),
('james', 'initial', 2, NULL, 'You walked in. The hour started. I want a clean opener.', 1),
('james', 'initial', 3, NULL, 'Soft hands are a tell. I notice. Lock in.', 1),
('james', 'initial', 4, NULL, 'This is not a warm chat. It is the first set. Honour it.', 1),
('james', 'initial', 5, NULL, 'I have thought about you on this floor. Now prove I was right.', 1),
('james', 'initial', 6, NULL, 'Feet set. Breath set. You do not get to hide in the unrack.', 1),
('james', 'initial', 7, NULL, 'I want you present. Not charming. Present.', 1),
('james', 'initial', 8, NULL, 'Simple. You start when I say. You start now.', 1),
('james', 'initial', 9, NULL, 'Do not look at the door. Look at the load I gave you.', 1),
('james', 'initial', 10, NULL, 'I am not here to be liked. I am here to see you take it.', 1),
('james', 'initial', 11, NULL, 'First inch. I watch that more than the last.', 1),
('james', 'initial', 12, NULL, 'You asked for me. This is what that costs.', 1),
('james', 'initial', 13, NULL, 'Quiet, man. Then move.', 1),
('james', 'initial', 14, NULL, 'I will be civil. I will not be soft. Unrack.', 1),
('james', 'initial', 15, NULL, 'If you came to negotiate, you came to the wrong room.', 1),
('james', 'mid', 0, NULL, 'Halfway is not mercy. It is the middle of the work.', 1),
('james', 'mid', 1, NULL, 'I want cleaner reps. I want them from you.', 1),
('james', 'mid', 2, NULL, 'That burn is information. Stay with it. I am.', 1),
('james', 'mid', 3, NULL, 'Do not invent a story. Do the next set.', 1),
('james', 'mid', 4, NULL, 'I should let you breathe. I will not. Brace.', 1),
('james', 'mid', 5, NULL, 'You are mine for this minute. Spend it lifting.', 1),
('james', 'mid', 6, NULL, 'Soft now and I will know. I always know.', 1),
('james', 'mid', 7, NULL, 'Look at me if you need a reason. Then lift.', 1),
('james', 'mid', 8, NULL, 'I want you tired and still honest.', 1),
('james', 'mid', 9, NULL, 'The easy part is over. That was the courtesy.', 1),
('james', 'mid', 10, NULL, 'Form first. Then I will allow the violence.', 1),
('james', 'mid', 11, NULL, 'Do not smile at the pain. Use it.', 1),
('james', 'mid', 12, NULL, 'I am still in the room. That is not a comfort. It is a fact.', 1),
('james', 'mid', 13, NULL, 'If you can talk, you can give me another rep.', 1),
('james', 'mid', 14, NULL, 'Mid-session is where people become quit. You will not.', 1),
('james', 'mid', 15, NULL, 'I want the next set more than I should. Give it to me.', 1),
('james', 'final', 0, NULL, 'Last third. This is the part I remember. So will you.', 1),
('james', 'final', 1, NULL, 'Those last two reps are mine. Deliver them.', 1),
('james', 'final', 2, NULL, 'I want you empty. Then I will let you leave.', 1),
('james', 'final', 3, NULL, 'Finish it. Make me certain I chose well.', 1),
('james', 'final', 4, NULL, 'Do not save anything for later. Later is not this set.', 1),
('james', 'final', 5, NULL, 'Pain is not the point. Obedience through the pain is.', 1),
('james', 'final', 6, NULL, 'Lock out like you intend to come back to me.', 1),
('james', 'final', 7, NULL, 'I will know if you cheat the last plate. Do not make me say it twice.', 1),
('james', 'final', 8, NULL, 'Stand up. Breathe. Take what is left. I want it.', 1),
('james', 'final', 9, NULL, 'This is how a man closes a session I ran.', 1),
('james', 'final', 10, NULL, 'Finish ugly if you must. Finish.', 1),
('james', 'final', 11, NULL, 'I should tell you to stop. I will not.', 1),
('james', 'final', 12, NULL, 'The clock does not release you. I do.', 1),
('james', 'final', 13, NULL, 'One more honest set. Then you may look at me.', 1),
('james', 'final', 14, NULL, 'Leave nothing I asked for in the rack.', 1),
('james', 'final', 15, NULL, 'Last call. Deliver, or explain yourself. I dislike explanations.', 1),
('james', 'exit', 0, NULL, 'Do not rack that weight. Get back under the bar. Quit is not a name I use for you.', 1),
('james', 'exit', 1, NULL, 'Did I dismiss you? I did not. Hands back on the bar.', 1),
('james', 'exit', 2, NULL, 'You do not walk out on a session you started. Return.', 1),
('james', 'exit', 3, NULL, 'Look at me. Are you my man, or is quit the name you want?', 1),
('james', 'exit', 4, NULL, 'Fatigue is a story. I want the next twenty percent. Now.', 1),
('james', 'exit', 5, NULL, 'Leave and you will carry it. Stay and I will still be hard. Pick.', 1),
('james', 'exit', 6, NULL, 'I did not give you permission. The set is open.', 1),
('james', 'exit', 7, NULL, 'Pain passes. Quit stays on your name. Pick up the bells.', 1),
('james', 'exit', 8, NULL, 'Stand up. Lock in. I am watching you. I want you back on the floor.', 1),
('james', 'exit', 9, NULL, 'You wanted results. The work is reps. Complete them.', 1),
('james', 'exit', 10, NULL, 'Stop pitying yourself. Sweat is not injury. Lift.', 1),
('james', 'exit', 11, NULL, 'You came here to submit to the work. Get to it.', 1),
('james', 'exit', 12, NULL, 'Do not spectate your own session. Maximum effort. Now.', 1),
('james', 'exit', 13, NULL, 'No negotiations. Handles. Push.', 1),
('james', 'exit', 14, NULL, 'You do not leave until every rep I named is done.', 1),
('james', 'exit', 15, NULL, 'Do not you dare give up on set three. Remember who this is for.', 1),
('james', 'exit', 16, NULL, 'Decide to be stronger than laziness. That is the only decision.', 1),
('james', 'exit', 17, NULL, 'Quiet. Lift. Do not rationalise quit to me.', 1),
('james', 'exit', 18, NULL, 'Leave the weak story. Lock into this set.', 1),
('james', 'exit', 19, NULL, 'Your progress lives in the reps you want to skip. Do them for me.', 1),
('james', 'exit', 20, NULL, 'Zero compromise. Deliver the full hour.', 1),
('james', 'exit', 21, NULL, 'Show me what you are. Mind in it. Now.', 1),
('james', 'exit', 22, NULL, 'Finish the job. Leave it on the floor, or do not come back asking for me.', 1),
('james', 'exit', 23, NULL, 'I want you under that bar. I will not ask a third time.', 1),
('james', 'complete', 0, NULL, 'You finished. I am not easy to impress. You managed it.', 1),
('james', 'complete', 1, NULL, 'The hour is done. I watched. I wanted you to see that I watched.', 1),
('james', 'complete', 2, NULL, 'You did not break. I am more relieved than I will admit.', 1),
('james', 'complete', 3, NULL, 'That last rep. I wanted it. You gave it. Come here.', 1),
('james', 'complete', 4, NULL, 'Proof. You can finish what you started. That matters more than the load.', 1),
('james', 'complete', 5, NULL, 'The tax is paid. In sweat. I find that acceptable.', 1),
('james', 'complete', 6, NULL, 'Another deposit. You are stronger than this morning. I noticed.', 1),
('james', 'complete', 7, NULL, 'You conquered the bar. Chest up, man. You are not quit.', 1),
('james', 'complete', 8, NULL, 'Discomfort became something I can use. You stayed. Good.', 1),
('james', 'complete', 9, NULL, 'No shortcuts. You did every thing I named. That is rare.', 1),
('james', 'complete', 10, NULL, 'Victory is a habit I intend to keep you in.', 1),
('james', 'complete', 11, NULL, 'The hard part is over. Now you will recover because I said so.', 1),
('james', 'complete', 12, NULL, 'You beat the man who walked in. I prefer this one.', 1),
('james', 'complete', 13, NULL, 'Pain leaves. What you did for me stays. I will remember it.', 1),
('james', 'complete', 14, NULL, 'Breathe, handsome. You pushed the edge I set. You won.', 1),
('james', 'complete', 15, NULL, 'Most people become quit. You did not. I wanted you not to.', 1),
('james', 'complete', 16, NULL, 'You faced it, took it, and came out on top. I am not done with you.', 1),
('james', 'complete', 17, NULL, 'Job done. You looked like you belonged to the work. You did.', 1),
('james', 'complete', 18, NULL, 'Character. Not just muscle. I asked for both.', 1),
('james', 'complete', 19, NULL, 'Walk out proud. You made me certain. That is not nothing.', 1),
('james', 'complete', 20, NULL, 'From the first unrack to the lockout, you were under control. Mine.', 1),
('james', 'complete', 21, NULL, 'Another brick. Serious work. I do not say that lightly.', 1),
('james', 'complete', 22, NULL, 'When it got heavy you found another gear. I wanted that gear.', 1),
('james', 'complete', 23, NULL, 'Recover properly. The session is won. Come home. I am not finished with you.', 1),
('james', 'bonus_complete', 1, NULL, 'You did not owe me that. You paid. Aftercare is the reward. You will take it.', 1),
('james', 'bonus_complete', 2, NULL, 'Extra. Come home. I want to look after you. That should bother me. Tonight it does not.', 1),
('james', 'bonus_complete', 3, NULL, 'Bonus locked. You went past the week. I look after you for that.', 1),
('james', 'bonus_complete', 4, NULL, 'The four-day men can watch. You stayed. I pay what I owe.', 1),
('james', 'bonus_complete', 5, NULL, 'You went past the week. Home. Sit. I have further care for you.', 1),
('james', 'optional_complete', 1, NULL, 'Optional locked. Ten minutes you did not owe. You paid them.', 1),
('james', 'optional_complete', 2, NULL, 'Easy work, real pounds. You stayed for the clock. I wanted that more than the theatre.', 1),
('james', 'optional_complete', 3, NULL, 'Five hundred on the house. Cheap if you stay. Costly if you skip. You stayed.', 1),
('james', 'optional_complete', 4, NULL, 'Extra minutes. Extra iron. I heard it. So did the board.', 1),
('james', 'optional_complete', 5, NULL, 'Warmup and cooldown count when you take them. You took them. Good man.', 1),
('james', 'set_up', 0, 'I LIKE THIS', 'The load is climbing. Stay with it.', 1),
('james', 'set_down', 0, 'That is not what we agreed', 'Put the weight back. I did not ask for less.', 1),
('james', 'hardness_1', 0, 'TOO EASY', 'A courtesy set. Next one we add. I want it to cost.', 1),
('james', 'hardness_2', 0, 'LIGHT', 'You had more. I felt it. Do not hide in light.', 1),
('james', 'hardness_3', 0, 'HONEST', 'A working set. Stay there or go up. I will allow either if it is true.', 1),
('james', 'hardness_4', 0, 'IT COST YOU', 'Good man. Hard is the point. I keep you there.', 1),
('james', 'hardness_5', 0, 'MAX', 'You emptied it. I saw that. I wanted to see it.', 1)
ON DUPLICATE KEY UPDATE title = VALUES(title), body = VALUES(body), is_active = 1;
