-- Week podium celebration lines. App falls back to code banks if missing.
-- Run on PlanetScale by hand. Re-run = duplicate ignore.
INSERT IGNORE INTO coach_lines (voice_id, bucket, sort_order, title, body, is_active) VALUES
('master', 'week_place_1', 1, NULL, 'You owned the week. Days and iron. The house saw it, man.', 1),
('master', 'week_place_1', 2, NULL, 'First. Not a vote. You took it. Good man.', 1),
('master', 'week_place_1', 3, NULL, 'Gold is not decoration. You paid for it in sessions.', 1),
('master', 'week_place_2', 1, NULL, 'Second. Close enough to hunt. I still mark you, man.', 1),
('master', 'week_place_2', 2, NULL, 'Silver. You showed. First still has a name. Take it next week.', 1),
('master', 'week_place_2', 3, NULL, 'Two is not last. Stay on the board.', 1),
('master', 'week_place_3', 1, NULL, 'Third. You are on the metal. That is not nothing, man.', 1),
('master', 'week_place_3', 2, NULL, 'Bronze. The house counted you. Do not make me drop you.', 1),
('master', 'week_place_3', 3, NULL, 'You placed. Soft men did not. Remember that.', 1),
('james', 'week_place_1', 1, NULL, 'You took the week. I wanted that. You have it.', 1),
('james', 'week_place_1', 2, NULL, 'First. I noticed. I meant to.', 1),
('james', 'week_place_1', 3, NULL, 'Gold. You showed up more, then you lifted more. That is how I keep score.', 1),
('james', 'week_place_2', 1, NULL, 'Second. I can still see you from first. Stay there.', 1),
('james', 'week_place_2', 2, NULL, 'Silver. Close. I do not do consolation. I do next week.', 1),
('james', 'week_place_2', 3, NULL, 'You placed. I wanted more. You can give it.', 1),
('james', 'week_place_3', 1, NULL, 'Third. You are on the board. I keep you there if you stay honest.', 1),
('james', 'week_place_3', 2, NULL, 'Bronze. Not first. Not gone. That is a choice I will watch.', 1),
('james', 'week_place_3', 3, NULL, 'You placed. Come back heavier. I will be here.', 1),
('luna', 'week_place_1', 1, NULL, 'You took the week. Quiet gold. Stay kind with it.', 1),
('luna', 'week_place_1', 2, NULL, 'First. You showed up and the work held. Beautiful.', 1),
('luna', 'week_place_1', 3, NULL, 'The house saw the week in you. Rest. Then keep it honest.', 1),
('luna', 'week_place_2', 1, NULL, 'Second. Close. Soft face. The work is still yours.', 1),
('luna', 'week_place_2', 2, NULL, 'Silver. You stayed with the week. That counts.', 1),
('luna', 'week_place_2', 3, NULL, 'You placed. Breathe. Next week is another floor.', 1),
('luna', 'week_place_3', 1, NULL, 'Third. You are on the metal. Carry that quietly.', 1),
('luna', 'week_place_3', 2, NULL, 'Bronze. You showed. That is enough to stand on.', 1),
('luna', 'week_place_3', 3, NULL, 'You placed. Soft finish. Come back present.', 1);
