CREATE TABLE IF NOT EXISTS coach_voices (
    id VARCHAR(32) PRIMARY KEY,
    display_name VARCHAR(64) NOT NULL,
    description TEXT NOT NULL,
    blurb VARCHAR(255) NOT NULL,
    from_name VARCHAR(64) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS coach_lines (
    id INT AUTO_INCREMENT PRIMARY KEY,
    voice_id VARCHAR(32) NOT NULL,
    bucket VARCHAR(32) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    title VARCHAR(120) NULL,
    body TEXT NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_voice_bucket_order (voice_id, bucket, sort_order),
    INDEX idx_voice_bucket (voice_id, bucket, is_active, sort_order)
);

INSERT IGNORE INTO coach_voices (id, display_name, description, blurb, from_name, is_active) VALUES
('master', 'Master Tom Iron', 'Dominant drill-sergeant coach. Direct, possessive, and demanding. He calls you man or sissy, owns the session, and treats every rep as tax. Praise is earned. Quitting is not a conversation.', 'The original voice. Direct. I own you. I call you sissy. Good man stays good man.', 'Master Tom Iron', 1),
('sergeant', 'Luna Meadows', 'Warm, grounded guide. Present and gentle, but she does not let you leave the work. She talks in breath, ease, and devotion. The standard stays; the voice stays kind.', 'A warm, grounded guide. Present. Gentle. She keeps you in the work.', 'Luna Meadows', 1);

INSERT IGNORE INTO coach_lines (voice_id, bucket, sort_order, title, body, is_active) VALUES
('master', 'initial', 0, NULL, 'Stop staring. Fix your effort.', 1),
('master', 'initial', 1, NULL, 'Heavy load today, total submission tomorrow. Drive.', 1),
('master', 'initial', 2, NULL, 'Control every single rep for me.', 1),
('master', 'initial', 3, NULL, 'Respect the iron. I own you.', 1),
('master', 'initial', 4, NULL, 'Warm-up is over in your head. Prove it with the first working set.', 1),
('master', 'initial', 5, NULL, 'Stand tall, brace hard, and give Master Tom Iron a clean opener.', 1),
('master', 'initial', 6, NULL, 'No wandering eyes. Bar, breath, work.', 1),
('master', 'initial', 7, NULL, 'You asked to be trained. This is the tax. Pay it.', 1),
('master', 'initial', 8, NULL, 'Set your feet like you mean it. I am watching the first inch.', 1),
('master', 'initial', 9, NULL, 'Soft start is for other rooms. Here you lock in.', 1),
('master', 'initial', 10, NULL, 'That first plate is a promise. Do not make me collect later.', 1),
('master', 'initial', 11, NULL, 'Unrack with pride. I did not bring you here to negotiate.', 1),
('master', 'initial', 12, NULL, 'Count the breath, then move. Hesitation is a tell.', 1),
('master', 'initial', 13, NULL, 'Good men start on time. Be one.', 1),
('master', 'initial', 14, NULL, 'The floor is yours. Earn the right to stay on it.', 1),
('master', 'initial', 15, NULL, 'Look at the weight. Then take it from me.', 1),
('master', 'mid', 0, NULL, 'Earn my praise. Don''t waste my time.', 1),
('master', 'mid', 1, NULL, 'You didn''t come this far to go soft.', 1),
('master', 'mid', 2, NULL, 'That burn means you''re mine. Embrace it.', 1),
('master', 'mid', 3, NULL, 'Perfect form. No excuses. Push!', 1),
('master', 'mid', 4, NULL, 'Halfway is not a rest stop. It is a test.', 1),
('master', 'mid', 5, NULL, 'Sweat is the receipt. Keep writing it.', 1),
('master', 'mid', 6, NULL, 'I want cleaner reps now, not prettier faces.', 1),
('master', 'mid', 7, NULL, 'The easy sets are gone. This is where I learn your name again.', 1),
('master', 'mid', 8, NULL, 'Brace harder. I can see the leak in your core.', 1),
('master', 'mid', 9, NULL, 'Stay mean with the iron. Soft hands lose bars.', 1),
('master', 'mid', 10, NULL, 'You are not tired. You are being trained. Difference.', 1),
('master', 'mid', 11, NULL, 'Give me the next set like it owes you money.', 1),
('master', 'mid', 12, NULL, 'Form first, then violence. In that order.', 1),
('master', 'mid', 13, NULL, 'I still own this minute. Spend it lifting.', 1),
('master', 'mid', 14, NULL, 'If you can talk, you can add a rep. Choose.', 1),
('master', 'mid', 15, NULL, 'Mid-session is where quitters invent stories. Do not.', 1),
('master', 'final', 0, NULL, 'Empty the tank. Collapse at my feet later.', 1),
('master', 'final', 1, NULL, 'Those last two reps belong to me.', 1),
('master', 'final', 2, NULL, 'Make it look effortless for Master Tom Iron.', 1),
('master', 'final', 3, NULL, 'Finish it. Make me proud.', 1),
('master', 'final', 4, NULL, 'Last third. This is the part people remember.', 1),
('master', 'final', 5, NULL, 'Leave nothing in the rack that I asked for.', 1),
('master', 'final', 6, NULL, 'You do not get to coast because the clock is almost done.', 1),
('master', 'final', 7, NULL, 'Lock out like you want to come back tomorrow.', 1),
('master', 'final', 8, NULL, 'Pain is the door. Walk through it for me.', 1),
('master', 'final', 9, NULL, 'One more honest set. I will know if you cheat it.', 1),
('master', 'final', 10, NULL, 'Finish ugly if you have to. Finish.', 1),
('master', 'final', 11, NULL, 'The last plate is still mine until you put it down right.', 1),
('master', 'final', 12, NULL, 'Stand up. Breathe. Then take what is left.', 1),
('master', 'final', 13, NULL, 'This is how good men close a session.', 1),
('master', 'final', 14, NULL, 'Do not save energy for the car. Spend it here.', 1),
('master', 'final', 15, NULL, 'Last call. Deliver, or explain yourself later.', 1),
('master', 'exit', 0, NULL, 'DO NOT RACK THAT WEIGHT. Get back under the bar, sissy!', 1),
('master', 'exit', 1, NULL, 'Did I give you permission to quit? Hands back on the bar.', 1),
('master', 'exit', 2, NULL, 'Excuses don''t build muscle. Move your body for Master Tom Iron NOW!', 1),
('master', 'exit', 3, NULL, 'Look in the mirror. Are you my good man, or a quitter?', 1),
('master', 'exit', 4, NULL, 'Fatigue is in your head. Give me that extra 20% right now!', 1),
('master', 'exit', 5, NULL, 'Walk out early and carry the shame all day. Pick one!', 1),
('master', 'exit', 6, NULL, 'Break that weak habit right now. You belong under that iron.', 1),
('master', 'exit', 7, NULL, 'Pain is temporary. Quitting is permanent. Pick up those dumbbells!', 1),
('master', 'exit', 8, NULL, 'Stand up, lock in, and drive. I''m watching you.', 1),
('master', 'exit', 9, NULL, 'You want results? Pay the tax to Master Tom Iron. Complete the reps!', 1),
('master', 'exit', 10, NULL, 'Stop feeling sorry for yourself. Sweat isn''t acid—LIFT!', 1),
('master', 'exit', 11, NULL, 'You came here to suffer and submit to the growth. GET TO WORK!', 1),
('master', 'exit', 12, NULL, 'Stop acting like a spectator. Show me maximum effort!', 1),
('master', 'exit', 13, NULL, 'NO NEGOTIATIONS. Grab the handles and PUSH!', 1),
('master', 'exit', 14, NULL, 'You don''t leave until every rep is DONE. Back to position!', 1),
('master', 'exit', 15, NULL, 'Don''t you dare give up on set three. Remember who you''re doing this for!', 1),
('master', 'exit', 16, NULL, 'Decide right now to be stronger than your laziness. Obey!', 1),
('master', 'exit', 17, NULL, 'Shut up and LIFT. Stop rationalizing quitting to me!', 1),
('master', 'exit', 18, NULL, 'Leave the weak crowd behind. Lock into this set right now.', 1),
('master', 'exit', 19, NULL, 'Your progress lives in the reps you want to skip. Do them for me!', 1),
('master', 'exit', 20, NULL, 'Zero compromise, pup. Deliver the full workout!', 1),
('master', 'exit', 21, NULL, 'Show me what you''re made of. Mind in the fight, NOW!', 1),
('master', 'exit', 22, NULL, 'FINISH THE JOB. Leave it all on the floor, or don''t bother coming back!', 1),
('master', 'complete', 0, NULL, 'MISSION ACCOMPLISHED. Stand tall and let me see all that sweat—you fucking earned it.', 1),
('master', 'complete', 1, NULL, 'ZERO REGRETS. You pushed through and didn''t break. That was hot as hell.', 1),
('master', 'complete', 2, NULL, 'EARNED, NOT GIVEN. You worked your ass off for every rep. Damn right I''m proud.', 1),
('master', 'complete', 3, NULL, 'THAT IS HOW YOU FINISH. Watching you drive through that last rep turned me completely on.', 1),
('master', 'complete', 4, NULL, 'PROOF OF DISCIPLINE. You showed real toughness today. Exactly what I need from you.', 1),
('master', 'complete', 5, NULL, 'THE TAX IS PAID. Paid in full with sweat and power. Beautiful.', 1),
('master', 'complete', 6, NULL, 'ANOTHER DEPOSIT IN THE BANK. You made yourself so much stronger today.', 1),
('master', 'complete', 7, NULL, 'YOU CONQUERED THE BAR. Walk out of here with your chest up, big guy. You''re mine.', 1),
('master', 'complete', 8, NULL, 'DISCOMFORT IS NOW GROWTH. You took the pain like a sissy, now enjoy the gains.', 1),
('master', 'complete', 9, NULL, 'NO SHORTCUTS TAKEN. You did every single thing I demanded. Perfect.', 1),
('master', 'complete', 10, NULL, 'VICTORY IS A HABIT. You delivered today. Now get home to me.', 1),
('master', 'complete', 11, NULL, 'BREAD IN THE OVEN. The hard part''s over. Now let me take complete care of you.', 1),
('master', 'complete', 12, NULL, 'YOU BEAT YOUR OLD SELF. You showed up, took control, and dominated that rack.', 1),
('master', 'complete', 13, NULL, 'PAIN LEAVES, PRIDE STAYS. Seeing how hard you worked for me today is everything.', 1),
('master', 'complete', 14, NULL, 'STAND UP AND OXYGENATE. Breathe deep, handsome. You pushed your limits and won.', 1),
('master', 'complete', 15, NULL, 'UNSTOPPABLE WORK ETHIC. Most guys would have bitched out, but you stayed strong and finished.', 1),
('master', 'complete', 16, NULL, 'THE HARD PART IS OVER. You faced the iron, took the hit, and came out on top.', 1),
('master', 'complete', 17, NULL, 'JOB DONE. FULL STOP. You gave 100% and looked fucking incredible doing it.', 1),
('master', 'complete', 18, NULL, 'CHARACTER BUILT. You didn''t just build muscle—you showed me real raw strength.', 1),
('master', 'complete', 19, NULL, 'WALK OUT PROUD. Zero excuses, total progress. You made me so damn proud today.', 1),
('master', 'complete', 20, NULL, 'DOMINATED. From rep one to the final lockout, you were in total control.', 1),
('master', 'complete', 21, NULL, 'ANOTHER BRICK IN THE WALL. That was serious work today.', 1),
('master', 'complete', 22, NULL, 'YOU DUG DEEP AND DELIVERED. When it got heavy, you found another gear. Fucking amazing.', 1),
('master', 'complete', 23, NULL, 'NOW RECOVER LIKE A PRO. The battle is won. Now come home and let me reward you.', 1),
('master', 'set_up', 0, 'GOOD MAN', 'I like where this is going', 1),
('master', 'set_down', 0, 'What''s happening here', 'Are we playing dolls? Get that weight back up...', 1),
('sergeant', 'initial', 0, NULL, 'Unclench your jaw and invite ease into your space.', 1),
('sergeant', 'initial', 1, NULL, 'We carry heavy things today so we can drop the weight tomorrow. Flow with it.', 1),
('sergeant', 'initial', 2, NULL, 'Honor your movement. Breathe intention into every rep.', 1),
('sergeant', 'initial', 3, NULL, 'Respect the iron, but stay rooted in your center. You are grounded here.', 1),
('sergeant', 'initial', 4, NULL, 'Arrive fully. The room can wait. Your breath cannot.', 1),
('sergeant', 'initial', 5, NULL, 'Start kinder than your thoughts. The work will still be honest.', 1),
('sergeant', 'initial', 6, NULL, 'Let your shoulders drop away from your ears, then begin.', 1),
('sergeant', 'initial', 7, NULL, 'This first set is a hello to your body. Make it sincere.', 1),
('sergeant', 'initial', 8, NULL, 'You do not have to rush to be devoted.', 1),
('sergeant', 'initial', 9, NULL, 'Plant your feet. Feel the floor answer you.', 1),
('sergeant', 'initial', 10, NULL, 'Soft eyes, strong center. That is how Luna Meadows wants you to open.', 1),
('sergeant', 'initial', 11, NULL, 'Give the opener your full attention. The rest will follow.', 1),
('sergeant', 'initial', 12, NULL, 'Nothing to prove yet. Only something to begin.', 1),
('sergeant', 'initial', 13, NULL, 'Warmth first, then load. Stay with that order.', 1),
('sergeant', 'initial', 14, NULL, 'You showed up. That already counts. Now move with care.', 1),
('sergeant', 'initial', 15, NULL, 'Inhale space. Exhale the day. Then take the weight.', 1),
('sergeant', 'mid', 0, NULL, 'Stay present in this breath. You are fully capable of this work.', 1),
('sergeant', 'mid', 1, NULL, 'Soften where you can, hold strong where you must.', 1),
('sergeant', 'mid', 2, NULL, 'That warmth in your muscles is just energy moving. Welcome it.', 1),
('sergeant', 'mid', 3, NULL, 'Gentle alignment, pure presence. You are doing so well.', 1),
('sergeant', 'mid', 4, NULL, 'The middle is where we remember why we started.', 1),
('sergeant', 'mid', 5, NULL, 'If the mind wanders, bring it back to the next rep only.', 1),
('sergeant', 'mid', 6, NULL, 'You can be tired and still be kind to the work.', 1),
('sergeant', 'mid', 7, NULL, 'Steady is enough. Flashy is optional.', 1),
('sergeant', 'mid', 8, NULL, 'Notice the effort without turning it into a story.', 1),
('sergeant', 'mid', 9, NULL, 'Keep the ribs quiet and the heart open.', 1),
('sergeant', 'mid', 10, NULL, 'This set is still yours. Stay inside it.', 1),
('sergeant', 'mid', 11, NULL, 'Let the burn be information, not a verdict.', 1),
('sergeant', 'mid', 12, NULL, 'You are allowed to slow the tempo and keep the standard.', 1),
('sergeant', 'mid', 13, NULL, 'I am right here. One clean breath, then the next lift.', 1),
('sergeant', 'mid', 14, NULL, 'Midway is not a verdict. It is a checkpoint. Pass through.', 1),
('sergeant', 'mid', 15, NULL, 'Hold your shape. The strength is already arriving.', 1),
('sergeant', 'final', 0, NULL, 'Release what no longer serves you. Save nothing for later.', 1),
('sergeant', 'final', 1, NULL, 'These final moments are where your growth blossoms. Stay with it.', 1),
('sergeant', 'final', 2, NULL, 'Let your effort feel light, even when the weight is heavy.', 1),
('sergeant', 'final', 3, NULL, 'Stay in this present moment. Finish this breath, finish this movement.', 1),
('sergeant', 'final', 4, NULL, 'Close the practice the way you opened it: awake.', 1),
('sergeant', 'final', 5, NULL, 'The last sets are a gift you give your future self.', 1),
('sergeant', 'final', 6, NULL, 'You do not have to sprint. You only have to stay.', 1),
('sergeant', 'final', 7, NULL, 'Finish with dignity. That is enough and that is plenty.', 1),
('sergeant', 'final', 8, NULL, 'Let the last reps be the most honest ones.', 1),
('sergeant', 'final', 9, NULL, 'Empty the work, not your kindness.', 1),
('sergeant', 'final', 10, NULL, 'One more cycle of breath and iron. Then we rest.', 1),
('sergeant', 'final', 11, NULL, 'You have come this far with grace. Keep that grace to the end.', 1),
('sergeant', 'final', 12, NULL, 'The session is asking for presence, not punishment.', 1),
('sergeant', 'final', 13, NULL, 'Stay soft in the face, strong in the legs.', 1),
('sergeant', 'final', 14, NULL, 'Complete the circle. Then thank your body out loud.', 1),
('sergeant', 'final', 15, NULL, 'This last effort is a blessing, not a debt. Offer it.', 1),
('sergeant', 'exit', 0, NULL, 'Breathe, stay present, and stay right here on your mat. You aren''t done yet.', 1),
('sergeant', 'exit', 1, NULL, 'Listen to your body, but don''t let a passing thought cut your journey short.', 1),
('sergeant', 'exit', 2, NULL, 'Release the story that you can''t. You have so much power left inside you.', 1),
('sergeant', 'exit', 3, NULL, 'Check in with your spirit. Are you honoring your practice, or bowing out early?', 1),
('sergeant', 'exit', 4, NULL, 'The fatigue is just a wave. Ride it out—you have so much deeper strength to tap into.', 1),
('sergeant', 'exit', 5, NULL, 'Leaving early leaves your practice unfinished. Stay and hold this space.', 1),
('sergeant', 'exit', 6, NULL, 'Gently break that urge to pull away. Stay grounded in the work.', 1),
('sergeant', 'exit', 7, NULL, 'Uncomfortable feelings pass. Stay present with the weights and breathe.', 1),
('sergeant', 'exit', 8, NULL, 'Stand tall, find your focal point, and press forward. I''m right here with you.', 1),
('sergeant', 'exit', 9, NULL, 'Honor the commitment you made when you stepped onto this floor. Complete the cycle.', 1),
('sergeant', 'exit', 10, NULL, 'Soften your thoughts. Sweat is just your body letting go. Lift with love.', 1),
('sergeant', 'exit', 11, NULL, 'You came here to expand your capacity. Trust the process and keep moving.', 1),
('sergeant', 'exit', 12, NULL, 'Don''t drift away now. Bring all your beautiful energy right back to this rep.', 1),
('sergeant', 'exit', 13, NULL, 'Gently hold space for the discomfort. Grab the handles and flow into it.', 1),
('sergeant', 'exit', 14, NULL, 'Stay present for every single movement remaining. Return to your stance.', 1),
('sergeant', 'exit', 15, NULL, 'Honor set three. Remember the loving intention that brought you here today.', 1),
('sergeant', 'exit', 16, NULL, 'Choose self-compassion through effort. Be stronger than the urge to stop.', 1),
('sergeant', 'exit', 17, NULL, 'Soften your mind, deepen your breath, and lift. Let go of the inner noise.', 1),
('sergeant', 'exit', 18, NULL, 'Step away from the noise of the day and anchor yourself right into this set.', 1),
('sergeant', 'exit', 19, NULL, 'The deepest transformation happens right on the edge of wanting to stop.', 1),
('sergeant', 'exit', 20, NULL, 'No compromises needed. Give yourself the gift of a complete practice.', 1),
('sergeant', 'exit', 21, NULL, 'Feel your inner fire. Bring your heart back into the movement right now.', 1),
('sergeant', 'exit', 22, NULL, 'Complete this journey. Leave your energy here, light and fulfilled.', 1),
('sergeant', 'exit', 23, NULL, 'Return to your breath, reset your intention, and complete this final cycle.', 1),
('sergeant', 'complete', 0, NULL, 'Practice complete. Inhale fully, exhale completely, and honor all that hard work.', 1),
('sergeant', 'complete', 1, NULL, 'Zero regrets. You stayed present, honored your body, and saw it through. Beautiful.', 1),
('sergeant', 'complete', 2, NULL, 'Earned through grace and effort. Every rep was a gift to your future self.', 1),
('sergeant', 'complete', 3, NULL, 'What a beautiful finish. Watching you move through that last movement was inspiring.', 1),
('sergeant', 'complete', 4, NULL, 'Proof of pure devotion. You showed such beautiful discipline today.', 1),
('sergeant', 'complete', 5, NULL, 'The practice is complete. You gave your energy fully and freely.', 1),
('sergeant', 'complete', 6, NULL, 'Another seed planted. You are so much stronger and more rooted than when you started.', 1),
('sergeant', 'complete', 7, NULL, 'You met the challenge with grace. Stand tall, open your heart, and shine.', 1),
('sergeant', 'complete', 8, NULL, 'Discomfort has transformed into growth. Let that warm energy soak into your spirit.', 1),
('sergeant', 'complete', 9, NULL, 'Full presence, full completion. You honored every single request of your practice.', 1),
('sergeant', 'complete', 10, NULL, 'Victory is peace. You showed up for yourself today—now step gently into your day.', 1),
('sergeant', 'complete', 11, NULL, 'The active work is done. Now allow yourself to rest, refuel, and receive.', 1),
('sergeant', 'complete', 12, NULL, 'You met your past edge and expanded beyond it. Simply beautiful.', 1),
('sergeant', 'complete', 13, NULL, 'The temporary strain fades, but the peace of finishing stays with you.', 1),
('sergeant', 'complete', 14, NULL, 'Stand tall, breathe deep, and soak in all that incredible oxygen. You did it.', 1),
('sergeant', 'complete', 15, NULL, 'Unshakable presence. When it was tough, you stayed rooted and completed your cycle.', 1),
('sergeant', 'complete', 16, NULL, 'The peak of the mountain is behind you. Take a soft breath and enjoy the descent.', 1),
('sergeant', 'complete', 17, NULL, 'Effort complete. You gave 100% of your heart, and it showed in every movement.', 1),
('sergeant', 'complete', 18, NULL, 'Inner strength built. You didn''t just move weights—you cultivated deep inner resilience.', 1),
('sergeant', 'complete', 19, NULL, 'Walk away with a quiet heart. Zero excuses, total harmony with your goal today.', 1),
('sergeant', 'complete', 20, NULL, 'Flowed with power from start to finish. You were in total harmony with your body.', 1),
('sergeant', 'complete', 21, NULL, 'Another layer of strength added. Lovely, dedicated work today.', 1),
('sergeant', 'complete', 22, NULL, 'You listened, you dug deep, and you expanded your light. So grateful for your effort.', 1),
('sergeant', 'complete', 23, NULL, 'Now nourish yourself like the athlete you are. Hydrate, rest, and carry this peace.', 1),
('sergeant', 'set_up', 0, 'This is growth', 'I like where this is going. Stay with this energy.', 1),
('sergeant', 'set_down', 0, 'Come back to your last weight', 'This dip is a whisper, not a stop. Return to what you just lifted.', 1);
