-- Partial snapshot. Prefer `npx tsx --env-file=.env.local scripts/apply-coach-catalog.ts`
-- for a full voice replace (already applied on prod 2026-09-04).
-- Reward / punishment rewrite: start, mid, last third, bonus, exit, resume, missed week, drop, hardness 1-2.
-- {name} is filled in the app as first name. Apply on PlanetScale by hand. Safe to re-run.

DELETE FROM coach_lines
WHERE bucket IN (
  'initial', 'mid', 'final', 'exit', 'bonus_complete', 'resume', 'missed_week', 'set_down', 'hardness_1', 'hardness_2'
);

INSERT INTO coach_lines (voice_id, bucket, sort_order, title, body, is_active) VALUES
('master', 'initial', 0, NULL, 'Look at the weight. Take it from me. This opener is growth if you take it clean.', 1),
('master', 'initial', 1, NULL, 'No wandering eyes. Bar, breath, work. That is how power gets into the first inch.', 1),
('master', 'initial', 2, NULL, 'You asked to be trained. Pay this set. Growth is built in the first inch, not later.', 1),
('master', 'initial', 3, NULL, 'Set your feet. I am watching the first inch. Mobility in the stance is what lets the power out.', 1),
('master', 'initial', 4, NULL, 'Soft start is for other rooms. Here you lock in. That is stamina for the whole hour.', 1),
('master', 'initial', 5, NULL, 'Unrack. I did not bring you here to negotiate. Lock this and the hour buys definition.', 1),
('master', 'initial', 6, NULL, 'Good men start on time. Be one. Lean does not wait for a mood.', 1),
('master', 'initial', 7, NULL, 'The floor is yours. Earn it. The man who stays gets the growth.', 1),
('master', 'initial', 8, NULL, 'Stop staring. Fix your effort. Sloppy openers do not buy power.', 1),
('master', 'initial', 9, NULL, 'Control every single rep for me. Control is mobility under load. That is how you stay lean.', 1),
('master', 'initial', 10, NULL, 'Respect the iron. I own this hour. Treat it right and you walk out with more definition.', 1),
('master', 'initial', 11, NULL, 'Warm-up is over in your head. Prove it. First working set is stamina, not theatre.', 1),
('master', 'initial', 12, NULL, 'Stand tall. Brace. Give me a clean opener. Clean now is power later.', 1),
('master', 'initial', 13, NULL, 'That first plate is a promise. Keep it and the growth belongs to you.', 1),
('master', 'initial', 14, NULL, 'Count the breath. Then move. Hesitation steals the stamina this set was going to leave.', 1),
('master', 'initial', 15, NULL, 'I am watching. Take the bar. I want to see the start of real definition.', 1),
('master', 'initial', 16, NULL, 'You don''t ask where we''re going. Sit under the bar. Hands on. That is how growth stays in the muscle.', 1),
('master', 'initial', 17, NULL, 'Stand straight. Carry yourself like the power already went up. Then make that true.', 1),
('master', 'initial', 18, NULL, 'I am structured. Match me on this first plate and the hour builds lean.', 1),
('master', 'mid', 0, NULL, 'You are not tired. You are being trained. Stay honest and the stamina sticks.', 1),
('master', 'mid', 1, NULL, 'Halfway is the test. Pass this set and the power is yours next week.', 1),
('master', 'mid', 2, NULL, 'That burn is the tissue working. Stay in it and it becomes definition.', 1),
('master', 'mid', 3, NULL, 'Brace harder. I can see the leak. Clean this up and the power gets out.', 1),
('master', 'mid', 4, NULL, 'I still own this minute. Spend it lifting. Minutes like this buy stamina.', 1),
('master', 'mid', 5, NULL, 'Form first. Then violence. Form is mobility. Violence is power. You need both.', 1),
('master', 'mid', 6, NULL, 'If you can talk, give me one more. That rep is lean. The easy out is not.', 1),
('master', 'mid', 7, NULL, 'Mid-session is where quit invents a story. Do not. Growth is in the set you want to skip.', 1),
('master', 'mid', 8, NULL, 'Don''t waste my time. Earn the definition, not a speech.', 1),
('master', 'mid', 9, NULL, 'You did not come this far to go soft. Soft now is less power.', 1),
('master', 'mid', 10, NULL, 'Sweat is the receipt. Keep writing it. That is lean being paid for.', 1),
('master', 'mid', 11, NULL, 'I want cleaner reps now. Not prettier faces. Clean reps are mobility you can see.', 1),
('master', 'mid', 12, NULL, 'The easy sets are gone. This is where stamina gets built. Stay.', 1),
('master', 'mid', 13, NULL, 'Stay mean with the iron. Soft hands lose bars, and lose the power with them.', 1),
('master', 'mid', 14, NULL, 'Give me the next set like it owes you growth.', 1),
('master', 'mid', 15, NULL, 'Perfect form. No excuses. Push. That is how definition shows.', 1),
('master', 'mid', 16, NULL, 'I don''t need you to think about it. Do it. Thinking does not buy stamina.', 1),
('master', 'mid', 17, NULL, 'You like being told what to do. Good. Do this set. It is the growth that sticks.', 1),
('master', 'mid', 18, NULL, 'What am I going to do with you? Put more power on you if you finish this one.', 1),
('master', 'final', 0, NULL, 'Those last two buy power. Deliver them.', 1),
('master', 'final', 1, NULL, 'Empty the tank. That empty is stamina you get to keep.', 1),
('master', 'final', 2, NULL, 'Finish it. The last third is where definition gets cut in.', 1),
('master', 'final', 3, NULL, 'Last third. This is the part that shows as lean.', 1),
('master', 'final', 4, NULL, 'Finish ugly if you have to. Finish. Ugly last sets still leave growth.', 1),
('master', 'final', 5, NULL, 'One more honest set. Cheat it and you cheat the mobility you just built.', 1),
('master', 'final', 6, NULL, 'The last plate is still mine until you put it down right. Put it down right and the power stays yours.', 1),
('master', 'final', 7, NULL, 'Last call. Deliver. Explanations do not add stamina.', 1),
('master', 'final', 8, NULL, 'Make it look effortless. Effort now is power on the next go.', 1),
('master', 'final', 9, NULL, 'Leave nothing in the rack that I asked for. What you finish here is growth you keep.', 1),
('master', 'final', 10, NULL, 'You do not get to coast because the clock is almost done. Coasting is less definition.', 1),
('master', 'final', 11, NULL, 'Lock out like you want more power tomorrow.', 1),
('master', 'final', 12, NULL, 'Pain is the door. Walk through it and the stamina starts here.', 1),
('master', 'final', 13, NULL, 'Stand up. Breathe. Take what is left. That leftover work is lean.', 1),
('master', 'final', 14, NULL, 'This is how good men close a session. They leave with more mobility than they brought.', 1),
('master', 'final', 15, NULL, 'Do not save energy for the car. Spend it here. That is the growth you get to keep.', 1),
('master', 'exit', 0, NULL, 'Do not rack that. Get back under the bar. Walk out and the growth stays on the floor.', 1),
('master', 'exit', 1, NULL, 'Look at me. {name}, or quit? Quit leaves the power here.', 1),
('master', 'exit', 2, NULL, 'No deal. I still own this session. Leave and you keep yesterday’s definition.', 1),
('master', 'exit', 3, NULL, 'Did I give you permission to quit? Hands back on the bar. Permission is the stamina you have not earned.', 1),
('master', 'exit', 4, NULL, 'Fatigue is a story. Give me that extra twenty percent. Now. Skip it and the lean does not move.', 1),
('master', 'exit', 5, NULL, 'Walk out and carry a softer hour all day. Or stay and keep the power. Pick.', 1),
('master', 'exit', 6, NULL, 'You belong under that iron. Get back. The mobility is in the set you are about to skip.', 1),
('master', 'exit', 7, NULL, 'Pain is temporary. Quit stays, and so does last week’s growth. Pick up the bells.', 1),
('master', 'exit', 8, NULL, 'Stand up. Lock in. Drive. Leave now and I watch the stamina walk out with you.', 1),
('master', 'exit', 9, NULL, 'You want results? Pay the tax. Incomplete reps do not buy definition.', 1),
('master', 'exit', 10, NULL, 'Stop feeling sorry for yourself. Sweat is not acid. Pity does not cut lean. Lift.', 1),
('master', 'exit', 11, NULL, 'You came here to submit to the work. Get to it. Submission is how the power lands. Walking is how it does not.', 1),
('master', 'exit', 12, NULL, 'Stop acting like a spectator. Spectators keep the same body. Maximum effort. Now.', 1),
('master', 'exit', 13, NULL, 'No negotiations. Grab the handles. Push. Negotiation is how growth dies in the doorway.', 1),
('master', 'exit', 14, NULL, 'You do not leave until every rep is done. Back to position. Half a session is half the stamina.', 1),
('master', 'exit', 15, NULL, 'Do not you dare give up on set three. Set three is the definition. Remember that.', 1),
('master', 'exit', 16, NULL, 'Decide to be stronger than laziness. Obey. Laziness is a lighter, softer week.', 1),
('master', 'exit', 17, NULL, 'Quiet. Lift. Do not explain quit to me. Explanations do not restore the power you just put down.', 1),
('master', 'exit', 18, NULL, 'Leave the weak story. Lock into this set. The story costs you lean.', 1),
('master', 'exit', 19, NULL, 'Your growth lives in the reps you want to skip. Do them. Skip them and it stays imaginary.', 1),
('master', 'exit', 20, NULL, 'Zero compromise. Deliver the full workout. Compromise is missed mobility.', 1),
('master', 'exit', 21, NULL, 'Show me what you are. Mind in the fight. A soft exit is a soft body. Now.', 1),
('master', 'exit', 22, NULL, 'Finish the job. Leave the work on the floor. Leave early and do not ask why the power did not show.', 1),
('master', 'exit', 23, NULL, 'I still own this hour. Get under the bar. This hour is the stamina. Rack it and you owe it.', 1),
('master', 'bonus_complete', 0, NULL, 'You did not owe me that, {name}. You paid. That extra work is growth already in the muscle.', 1),
('master', 'bonus_complete', 1, NULL, 'Extra credit. The four-day men stay the same. You bought more stamina.', 1),
('master', 'bonus_complete', 2, NULL, '{name}. That is definition, not decoration.', 1),
('master', 'bonus_complete', 3, NULL, 'The four-day men can watch. You stayed. The next upper will show the power.', 1),
('master', 'bonus_complete', 4, NULL, 'You went past the week. Rest so the lean can land. Mobility stays if you let it settle.', 1),
('master', 'resume', 0, NULL, '{name}. The growth already started without you. Get under the bar or stay yesterday.', 1),
('master', 'missed_week', 0, NULL, 'Oh, sorry... were you busy?
The power took the week off with {name}. So did the lean.', 1),
('master', 'set_down', 0, 'That is not the load', 'Put it back. Less here is less power. I did not ask you to stall the growth.', 1),
('master', 'hardness_1', 0, 'TOO EASY', 'That was a warm handshake, {name}. No definition in a handshake. Next set we add.', 1),
('master', 'hardness_2', 0, 'LIGHT WORK', 'You had more in the tank. I felt it. You left the stamina sitting there.', 1),
('james', 'initial', 0, NULL, 'Look at me. Then take the first plate. A clean opener is how growth starts to count.', 1),
('james', 'initial', 1, NULL, 'Take the bar. I want a start that turns into power later.', 1),
('james', 'initial', 2, NULL, 'You walked in. The hour started. I want a start that shows as definition.', 1),
('james', 'initial', 3, NULL, 'Soft hands are a tell. Lock in. Power does not come from a loose unrack.', 1),
('james', 'initial', 4, NULL, 'This is not a warm chat. It is the first set. Honour it and the stamina has somewhere to go.', 1),
('james', 'initial', 5, NULL, 'You are on this floor. Prove the hour. A serious start is lean you can keep.', 1),
('james', 'initial', 6, NULL, 'Feet set. Breath set. Hide in the unrack and you hide the mobility.', 1),
('james', 'initial', 7, NULL, 'I want you present. Not charming. Present reps are the ones that add growth.', 1),
('james', 'initial', 8, NULL, 'Simple. You start now. Late starts do not build power.', 1),
('james', 'initial', 9, NULL, 'Do not look at the door. Look at the load. That load is how you get lean.', 1),
('james', 'initial', 10, NULL, 'I am not here to be liked. I am here to see you take it, and keep the definition.', 1),
('james', 'initial', 11, NULL, 'First inch. I watch that more than the last. Steal it and you steal the stamina.', 1),
('james', 'initial', 12, NULL, 'You asked for me. This is what that costs: honest first reps, then visible growth.', 1),
('james', 'initial', 13, NULL, 'Quiet, {name}. Then move. The talking is not the power.', 1),
('james', 'initial', 14, NULL, 'I will be civil. I will not be soft. Unrack. Soft is less definition next time.', 1),
('james', 'initial', 15, NULL, 'If you came to negotiate, you came to the wrong room. The set is how mobility under load improves.', 1),
('james', 'mid', 0, NULL, 'Halfway is not mercy. Stay with it and the stamina shows next time.', 1),
('james', 'mid', 1, NULL, 'I want cleaner reps from you. Clean is mobility. That turns into power.', 1),
('james', 'mid', 2, NULL, 'That burn is information. Stay with it. That is definition being cut.', 1),
('james', 'mid', 3, NULL, 'Do not invent a story. Do the next set. Stories do not make you lean.', 1),
('james', 'mid', 4, NULL, 'Brace. Breath is for the next rep, not an exit. Stay and the growth counts.', 1),
('james', 'mid', 5, NULL, 'This minute is the session. Spend it lifting. That is how power lands.', 1),
('james', 'mid', 6, NULL, 'Soft now and I will know. Stay honest and I will see more definition next time.', 1),
('james', 'mid', 7, NULL, 'If you need a reason: this set is the stamina. Then lift.', 1),
('james', 'mid', 8, NULL, 'I want you tired and still honest. Honest tired is lean that sticks.', 1),
('james', 'mid', 9, NULL, 'The easy part is over. The rest is where the growth is.', 1),
('james', 'mid', 10, NULL, 'Form first. Then the violence. Form is mobility. Then I will allow the power.', 1),
('james', 'mid', 11, NULL, 'Do not smile at the pain. Use it. That is definition arriving.', 1),
('james', 'mid', 12, NULL, 'I am still in the room. Stay in the set. Leaving it early leaves the stamina.', 1),
('james', 'mid', 13, NULL, 'If you can talk, give me another rep. That one is growth.', 1),
('james', 'mid', 14, NULL, 'Mid-session is where people become quit. You will not. The power is still in the rack.', 1),
('james', 'mid', 15, NULL, 'I want the next set done properly. Give it to me. I will expect more lean for it.', 1),
('james', 'final', 0, NULL, 'Last third. This is the part that shows as definition. So will you.', 1),
('james', 'final', 1, NULL, 'Those last two buy power. Deliver them and the lockout remembers.', 1),
('james', 'final', 2, NULL, 'I want you empty. Empty now is stamina you bring back.', 1),
('james', 'final', 3, NULL, 'Finish it. Make the last third count. That is the growth that shows up next week.', 1),
('james', 'final', 4, NULL, 'Do not save anything for later. Later is more lean, and you buy it now.', 1),
('james', 'final', 5, NULL, 'Pain is not the point. Staying through it is. That is the stamina.', 1),
('james', 'final', 6, NULL, 'Lock out like you intend to come back with more power.', 1),
('james', 'final', 7, NULL, 'I will know if you cheat the last plate. Cheat it and you cheat the definition.', 1),
('james', 'final', 8, NULL, 'Stand up. Breathe. Take what is left. That leftover work is mobility under fatigue.', 1),
('james', 'final', 9, NULL, 'This is how a man closes a session I ran. He leaves with more growth than he brought.', 1),
('james', 'final', 10, NULL, 'Finish ugly if you must. Finish. Ugly last reps still cut lean.', 1),
('james', 'final', 11, NULL, 'I should tell you to stop. I will not. Stopping now leaves the power where it was.', 1),
('james', 'final', 12, NULL, 'The clock does not release you. The last honest set does. Then you have stamina I can add to.', 1),
('james', 'final', 13, NULL, 'One more honest set. Then you have growth I can add to.', 1),
('james', 'final', 14, NULL, 'Leave nothing I asked for in the rack. What you finish here is definition you keep.', 1),
('james', 'final', 15, NULL, 'Last call. Deliver. I dislike explanations. They do not add mobility.', 1),
('james', 'exit', 0, NULL, 'Do not rack that weight. Get back under the bar. Walk out and the growth stays here.', 1),
('james', 'exit', 1, NULL, 'Did I dismiss you? I did not. Hands back on the bar. I did not dismiss the power either.', 1),
('james', 'exit', 2, NULL, 'You do not walk out on a session you started. Return. A walkout is last week’s definition.', 1),
('james', 'exit', 3, NULL, 'Look at me. Stay, or let quit keep the lean. Pick.', 1),
('james', 'exit', 4, NULL, 'Fatigue is a story. I want the next twenty percent. Now. Skip it and the stamina does not move.', 1),
('james', 'exit', 5, NULL, 'Leave and you will carry a softer hour. Stay and the power still has a chance. Pick.', 1),
('james', 'exit', 6, NULL, 'I did not give you permission. The set is open. Permission is growth you have not finished.', 1),
('james', 'exit', 7, NULL, 'Pain passes. Quit stays on your name, and so does last week’s body. Pick up the bells.', 1),
('james', 'exit', 8, NULL, 'Stand up. Lock in. I am watching you. I want the mobility back on the floor.', 1),
('james', 'exit', 9, NULL, 'You wanted results. The work is reps. Incomplete reps do not buy definition.', 1),
('james', 'exit', 10, NULL, 'Stop pitying yourself. Sweat is not injury. Pity does not cut lean. Lift.', 1),
('james', 'exit', 11, NULL, 'You came here to submit to the work. Get to it. Walking is how the power misses you.', 1),
('james', 'exit', 12, NULL, 'Do not spectate your own session. Spectators keep the same growth. Maximum effort. Now.', 1),
('james', 'exit', 13, NULL, 'No negotiations. Handles. Push. Negotiation is how stamina dies in the doorway.', 1),
('james', 'exit', 14, NULL, 'You do not leave until every rep I named is done. Half a session is half the lean.', 1),
('james', 'exit', 15, NULL, 'Do not you dare give up on set three. Set three is the definition. Remember that.', 1),
('james', 'exit', 16, NULL, 'Decide to be stronger than laziness. That is the only decision. Laziness is a lighter, softer week.', 1),
('james', 'exit', 17, NULL, 'Quiet. Lift. Do not rationalise quit to me. Talk does not restore the power you just put down.', 1),
('james', 'exit', 18, NULL, 'Leave the weak story. Lock into this set. The story costs you growth.', 1),
('james', 'exit', 19, NULL, 'Your growth lives in the reps you want to skip. Do them. Skip them and it stays imaginary.', 1),
('james', 'exit', 20, NULL, 'Zero compromise. Deliver the full hour. Compromise is missed mobility.', 1),
('james', 'exit', 21, NULL, 'Show me what you are. Mind in it. A soft exit is a soft body. Now.', 1),
('james', 'exit', 22, NULL, 'Finish the job. Leave the work on the floor. Leave early and do not ask why the definition did not show.', 1),
('james', 'exit', 23, NULL, 'I want you under that bar. I will not ask a third time. The stamina is still on it.', 1),
('james', 'bonus_complete', 0, NULL, 'You did not owe me that. You paid. That extra work will show as growth.', 1),
('james', 'bonus_complete', 1, NULL, 'Extra. I noticed. So will the stamina next session.', 1),
('james', 'bonus_complete', 2, NULL, 'Bonus locked. You went past the week. I will expect more definition for it.', 1),
('james', 'bonus_complete', 3, NULL, 'The four-day men can watch. You stayed. That is power, not theatre.', 1),
('james', 'bonus_complete', 4, NULL, 'You went past the week. Rest properly. The lean has to land.', 1),
('james', 'resume', 0, NULL, 'You left it open. The growth did not wait. Finish it or keep yesterday’s numbers.', 1),
('james', 'missed_week', 0, NULL, '{name}. The week closed. You did not. So the power did not. I noticed the gap.', 1),
('james', 'set_down', 0, 'That is not what we agreed', 'Put the weight back. Less here is less power. I did not ask you to pause the lean.', 1),
('james', 'hardness_1', 0, 'TOO EASY', 'A courtesy set. Courtesy does not cut definition. Next one we add.', 1),
('james', 'hardness_2', 0, 'LIGHT', 'You had more. I felt it. You hid the stamina in light.', 1),
('luna', 'initial', 0, NULL, 'Unclench your jaw. Soft face. Then take the first plate. A kind start still buys growth.', 1),
('luna', 'initial', 1, NULL, 'We carry heavy things today. Breathe in. Begin. This is how power arrives.', 1),
('luna', 'initial', 2, NULL, 'Honor the movement. One clean breath into every rep. Clean reps are mobility you get to keep.', 1),
('luna', 'initial', 3, NULL, 'Respect the iron. Stay rooted. You are here. That is enough to start building stamina.', 1),
('luna', 'initial', 4, NULL, 'Arrive fully. The room can wait. Your breath cannot. Presence is what lets the definition land.', 1),
('luna', 'initial', 5, NULL, 'Start kinder than your thoughts. The work will still be honest, and it will still make you lean.', 1),
('luna', 'initial', 6, NULL, 'Shoulders away from your ears. Then begin. Soft shoulders. Room for mobility. Then the work.', 1),
('luna', 'initial', 7, NULL, 'This first set is a hello. Make it sincere. Sincere work is growth the muscle can use.', 1),
('luna', 'initial', 8, NULL, 'You do not have to rush. You do have to start. Stamina begins with the first honest rep.', 1),
('luna', 'initial', 9, NULL, 'Plant your feet. Feel the floor. Then move. That is how power stays in you.', 1),
('luna', 'initial', 10, NULL, 'Soft eyes. Strong center. That is how we open, and how definition starts to show.', 1),
('luna', 'initial', 11, NULL, 'Give the opener your full attention. The rest will follow, including the lean.', 1),
('luna', 'initial', 12, NULL, 'Nothing to prove yet. Only something to begin. Begin, and the body can start to keep the growth.', 1),
('luna', 'initial', 13, NULL, 'Warmth first. Then load. Stay with that order and the mobility will let you take more later.', 1),
('luna', 'initial', 14, NULL, 'You showed up. That already counts. Move with care and the stamina can use it.', 1),
('luna', 'initial', 15, NULL, 'Inhale space. Exhale the day. Then take the weight. Leave the day. Keep the power.', 1),
('luna', 'mid', 0, NULL, 'Stay. The shake is welcome. That shake is growth arriving.', 1),
('luna', 'mid', 1, NULL, 'Soften the face. Hold the middle. The body that stays here keeps the stamina.', 1),
('luna', 'mid', 2, NULL, 'That burn is just energy moving. Stay with it. It is definition being cut.', 1),
('luna', 'mid', 3, NULL, 'Align. Then keep going. Clean shape now is mobility. Stronger shape next time.', 1),
('luna', 'mid', 4, NULL, 'The middle is where we remember why we started: lean you can carry.', 1),
('luna', 'mid', 5, NULL, 'If the mind wanders, bring it back to the next rep. That is the power that stays.', 1),
('luna', 'mid', 6, NULL, 'You can be tired and still be kind to the work. Kind and tired still builds stamina.', 1),
('luna', 'mid', 7, NULL, 'Steady is enough. Flashy is optional. Steady is what adds growth.', 1),
('luna', 'mid', 8, NULL, 'Notice the effort. Do not turn it into a story. Effort is the lean starting.', 1),
('luna', 'mid', 9, NULL, 'Ribs quiet. Heart open. Next rep. Stay in shape so the mobility can hold.', 1),
('luna', 'mid', 10, NULL, 'This set is still yours. Stay inside it and it becomes definition.', 1),
('luna', 'mid', 11, NULL, 'Let the burn be information, not a verdict. It is the tissue changing. Growth.', 1),
('luna', 'mid', 12, NULL, 'You may slow the tempo. Keep the standard. Slow and honest still makes power.', 1),
('luna', 'mid', 13, NULL, 'I am right here. One clean breath. Then the next lift. We are building stamina you can carry.', 1),
('luna', 'mid', 14, NULL, 'Midway is not a verdict. It is a checkpoint. Pass through and the second half still counts as lean.', 1),
('luna', 'mid', 15, NULL, 'Hold your shape. The growth is already arriving. Do not rush it off.', 1),
('luna', 'final', 0, NULL, 'Stay. This is the hard part. These last sets are the growth the body keeps.', 1),
('luna', 'final', 1, NULL, 'These last moments are where it counts. Stay. This is the stamina.', 1),
('luna', 'final', 2, NULL, 'Let the effort feel light. The weight is not. Moving it anyway is power.', 1),
('luna', 'final', 3, NULL, 'This breath. This movement. Then the next. That is how definition settles in.', 1),
('luna', 'final', 4, NULL, 'Close the way you opened. Awake. A present finish is lean you can start with next time.', 1),
('luna', 'final', 5, NULL, 'The last sets are a gift to the body that stayed. It will have more mobility next time.', 1),
('luna', 'final', 6, NULL, 'You do not have to sprint. You only have to stay. Staying is how stamina grows.', 1),
('luna', 'final', 7, NULL, 'Finish with dignity. That is enough. Honest last reps become next week’s power.', 1),
('luna', 'final', 8, NULL, 'Let the last reps be the most honest ones. Those are the ones that stay as growth.', 1),
('luna', 'final', 9, NULL, 'Empty the work. Keep the kindness. Empty now is more definition later.', 1),
('luna', 'final', 10, NULL, 'One more cycle of breath and iron. Then we rest so the lean can settle.', 1),
('luna', 'final', 11, NULL, 'You have come this far. Keep that grace to the end. The end is still building mobility.', 1),
('luna', 'final', 12, NULL, 'The session is asking for presence. Not punishment. Presence is what the muscle can use for growth.', 1),
('luna', 'final', 13, NULL, 'Soft face. Strong legs. Hold. That hold is power arriving.', 1),
('luna', 'final', 14, NULL, 'Complete the circle. Then thank your body. It just got stamina it can keep.', 1),
('luna', 'final', 15, NULL, 'This last effort is not a debt. Offer it. The definition is already becoming yours.', 1),
('luna', 'exit', 0, NULL, 'Breathe. Stay on the floor. Leave now and the growth stays unfinished.', 1),
('luna', 'exit', 1, NULL, 'Listen to your body. A passing thought is not the work. End it early and the stamina does not land.', 1),
('luna', 'exit', 2, NULL, 'Release the story that you cannot. You have more. The story costs you power.', 1),
('luna', 'exit', 3, NULL, 'Are you honoring the work, or leaving early? Leave and the definition does not get to finish. Stay.', 1),
('luna', 'exit', 4, NULL, 'Fatigue is a wave. Ride it. Step off and the lean waits until next time.', 1),
('luna', 'exit', 5, NULL, 'Leaving now leaves it unfinished. Stay and hold. Unfinished is missed mobility.', 1),
('luna', 'exit', 6, NULL, 'That urge to go is just an urge. Come back to the bar. The urge does not build growth.', 1),
('luna', 'exit', 7, NULL, 'Uncomfortable feelings pass. Stay with the weight. Breathe. Passing feelings should not take the power with them.', 1),
('luna', 'exit', 8, NULL, 'Stand tall. Find a point. Press. Soften out now and the stamina walks with you.', 1),
('luna', 'exit', 9, NULL, 'You stepped onto this floor for a reason. Complete it. A short session is a short week for definition.', 1),
('luna', 'exit', 10, NULL, 'Soften the thoughts. Sweat is just the body letting go. Pity does not cut lean. Lift.', 1),
('luna', 'exit', 11, NULL, 'You came here to expand. Trust that. Keep moving. Stopping here stops the growth.', 1),
('luna', 'exit', 12, NULL, 'Do not drift. Bring everything back to this rep. Drift is how mobility leaves the set.', 1),
('luna', 'exit', 13, NULL, 'Hold the discomfort. Hands on. Flow into it. Dropping it drops the power.', 1),
('luna', 'exit', 14, NULL, 'Every movement still left is yours. Return to your stance. What you skip does not become stamina.', 1),
('luna', 'exit', 15, NULL, 'Honor set three. Set three is the definition. Remember why you began.', 1),
('luna', 'exit', 16, NULL, 'Be kind. And stay. The urge to stop is kind to yesterday’s body, not to you.', 1),
('luna', 'exit', 17, NULL, 'Soften the mind. Deepen the breath. Lift. A soft exit is still a lost set of lean.', 1),
('luna', 'exit', 18, NULL, 'Leave the day outside. This set is the only room. Take the day back in and you take the growth out.', 1),
('luna', 'exit', 19, NULL, 'The edge of wanting to stop is where it changes. Stay. That edge is the stamina.', 1),
('luna', 'exit', 20, NULL, 'No bargain. Give yourself a complete session. A bargain is missed power.', 1),
('luna', 'exit', 21, NULL, 'Bring the heart back into the movement. Now. Half-heart is half the definition.', 1),
('luna', 'exit', 22, NULL, 'Finish this. Leave the work here. Then rest. Rest after. Not instead of the lean.', 1),
('luna', 'exit', 23, NULL, 'Return to the breath. Reset. Complete the cycle. An open cycle does not keep the mobility.', 1),
('luna', 'bonus_complete', 0, NULL, 'You did not owe me that. You gave it. That extra work is already growth. Rest so it can stay.', 1),
('luna', 'bonus_complete', 1, NULL, 'Extra work. Be kind to the body that stayed. It will have more power to give.', 1),
('luna', 'bonus_complete', 2, NULL, 'Bonus locked. You went past the week. The body will have more stamina next time.', 1),
('luna', 'bonus_complete', 3, NULL, 'I see the extra you gave. Beautiful. Now rest. Let it become definition on the next floor.', 1),
('luna', 'bonus_complete', 4, NULL, 'You did not have to stay. You stayed. Carry that as lean and mobility, quietly.', 1),
('luna', 'resume', 0, NULL, 'The session is still open. The growth is waiting on the floor. Come back or it will not stay.', 1),
('luna', 'missed_week', 0, NULL, '{name}. Last week closed without you. Softly said: the stamina did not get built. Come back present.', 1),
('luna', 'set_down', 0, 'Come back to your last weight', 'This dip is a whisper. Stay here and the power stays a whisper too. Return to what you just lifted.', 1),
('luna', 'hardness_1', 0, 'Too easy', 'Your body had more. A light set does not cut definition. We add. Softly.', 1),
('luna', 'hardness_2', 0, 'Light', 'Gentle is fine. Too gentle leaves the growth on the table.', 1);
